jobs:
    footwear_product_import:
        connector: Akeneo CSV Connector
        alias:     product_import
        label:     Footwear product import
        type:      import
        configuration:
            reader:
                filePath:      /tmp/product_import/product_import.csv
                uploadAllowed: true
                delimiter:     ;
                enclosure:     '"'
                escape:        '\'
            processor:
                enabled:          true
                categoriesColumn: categories
                familyColumn:     family
                groupsColumn:     groups
    footwear_product_export:
        connector: Akeneo CSV Connector
        alias:     product_export
        label:     Footwear product export
        type:      export
        configuration:
            reader:
                channel: mobile
            processor:
                channel:    mobile
                delimiter:  ;
                enclosure:  '"'
                withHeader: true
            writer:
                directoryName: /tmp/product_export
                fileName:      product_export.csv
    footwear_category_import:
        connector: Akeneo CSV Connector
        alias:     category_import
        label:     Footwear category import
        type:      import
        configuration:
            reader:
                filePath:      /tmp/category_import/category_import.csv
                uploadAllowed: true
                delimiter:     ;
                enclosure:     '"'
                escape:        '\'
            processor:
                circularRefsChecked: true
    footwear_category_export:
        connector: Akeneo CSV Connector
        alias:     category_export
        label:     Footwear category export
        type:      export
        configuration:
            processor:
                delimiter:  ;
                enclosure:  '"'
                withHeader: true
            writer:
                directoryName: /tmp/category_export
                fileName:      category_export.csv
    footwear_attribute_import:
        connector:     Akeneo CSV Connector
        alias:         attribute_import
        label:         Footwear attribute import
        type:          import
        configuration: ~
    footwear_attribute_export:
        connector: Akeneo CSV Connector
        alias:     attribute_export
        label:     Footwear attribute export
        type:      export
        configuration:
            processor:
                delimiter:  ;
                enclosure:  '"'
                withHeader: true
            writer:
                directoryName: /tmp/attribute_export
                fileName:      attribute_export.csv
    footwear_association_import:
        connector: Akeneo CSV Connector
        alias:     association_import
        label:     Footwear association import
        type:      import
        configuration:
            reader:
                filePath:      /tmp/association_import/association_import.csv
                uploadAllowed: true
                delimiter:     ;
                enclosure:     '"'
                escape:        '\'
    footwear_association_export:
        connector: Akeneo CSV Connector
        alias:     association_export
        label:     Footwear association export
        type:      export
        configuration:
            processor:
                delimiter:  ;
                enclosure:  '"'
                withHeader: true
            writer:
                directoryName: /tmp/association_export
                fileName:      association_export.csv
    footwear_group_import:
        connector: Akeneo CSV Connector
        alias:     group_import
        label:     Footwear group import
        type:      import
        configuration:
            reader:
                filePath:      /tmp/group_import/group_import.csv
                uploadAllowed: true
                delimiter:     ;
                enclosure:     '"'
                escape:        '\'
    footwear_group_export:
        connector: Akeneo CSV Connector
        alias:     group_export
        label:     Footwear group export
        type:      export
        configuration:
            processor:
                delimiter:  ;
                enclosure:  '"'
                withHeader: true
            writer:
                directoryName: /tmp/group_export
                fileName:      group_export.csv
