jobs:
    footwear_product_import:
        connector: Akeneo CSV Connector
        alias:     csv_product_import
        label:     Footwear product import
        type:      import
        configuration:
            filePath:           /tmp/product_import/product_import.csv
            uploadAllowed:      true
            delimiter:          ;
            enclosure:          '"'
            escape:             '\'
            enabled:            true
            categoriesColumn:   categories
            familyColumn:       family
            groupsColumn:       groups
            realTimeVersioning: true
    footwear_product_export:
        connector: Akeneo CSV Connector
        alias:     csv_product_export
        label:     Footwear product export
        type:      export
        configuration:
            channel:    mobile
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/product_export/product_export.csv
    footwear_category_import:
        connector: Akeneo CSV Connector
        alias:     csv_category_import
        label:     Footwear category import
        type:      import
        configuration:
            filePath:            /tmp/category_import/category_import.csv
            uploadAllowed:       true
            delimiter:           ;
            enclosure:           '"'
            escape:              '\'
            circularRefsChecked: true
    footwear_category_export:
        connector: Akeneo CSV Connector
        alias:     csv_category_export
        label:     Footwear category export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/category_export/category_export.csv
    footwear_association_import:
        connector: Akeneo CSV Connector
        alias:     csv_association_import
        label:     Footwear association import
        type:      import
        configuration:
            filePath:      /tmp/association_import/association_import.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    footwear_association_export:
        connector: Akeneo CSV Connector
        alias:     csv_association_export
        label:     Footwear association export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/association_export/association_export.csv
    footwear_group_import:
        connector: Akeneo CSV Connector
        alias:     csv_group_import
        label:     Footwear group import
        type:      import
        configuration:
            filePath:      /tmp/group_import/group_import.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    footwear_group_export:
        connector: Akeneo CSV Connector
        alias:     csv_group_export
        label:     Footwear group export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/group_export/group_export.csv
    footwear_attribute_import:
        connector: Akeneo CSV Connector
        alias:     csv_attribute_import
        label:     Footwear attribute import
        type:      import
        configuration:
            filePath:      /tmp/attribute_import/attribute_import.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    footwear_attribute_export:
        connector: Akeneo CSV Connector
        alias:     csv_attribute_export
        label:     Footwear attribute export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/attribute_export/attribute_export.csv
    footwear_option_import:
        connector: Akeneo CSV Connector
        alias:     csv_attribute_option_import
        label:     Footwear option import
        type:      import
        configuration:
            filePath:      /tmp/attribute_import/option_import.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    footwear_option_export:
        connector: Akeneo CSV Connector
        alias:     csv_attribute_option_export
        label:     Footwear option export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/option_export/option_export.csv
