Pim\Bundle\CatalogBundle\Entity\GroupType:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        code:
            - NotBlank: ~
            - Regex:
                pattern: /^[a-zA-Z0-9_]+$/
                message: Group type code may contain only letters, numbers and underscores.
            - Length:
                max: 50
        translations:
            - Valid: ~

Pim\Bundle\CatalogBundle\Entity\GroupTypeTranslation:
    properties:
        label:
            - Length:
                max: 100
