Pim\Bundle\CatalogBundle\Model\Group:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
        - Pim\Bundle\CatalogBundle\Validator\Constraints\UniqueVariantAxis:
            message: Product "%product%" cannot be added to the the variant group "%variant group%" because it already contains another product with values "%values%".
        - Pim\Bundle\CatalogBundle\Validator\Constraints\Immutable:
            properties:
                - code
                - type
                - attributes
    properties:
        code:
            - NotBlank: ~
            - Regex:
                pattern: /^[a-zA-Z0-9_]+$/
                message: Group code may contain only letters, numbers and underscores.
            - Length:
                max: 50
        translations:
            - Valid: ~
        attributes:
            - Count:
                min: 1
                groups: [variant]

Pim\Bundle\CatalogBundle\Model\GroupTranslation:
    properties:
        label:
            - Length:
                max: 100
