parameters:
    pim_import_export.event_listener.archivist.class:                 Pim\Bundle\ImportExportBundle\EventListener\JobExecutionArchivist
    pim_import_export.event_listener.invalid_items_collector.class:   Pim\Bundle\ImportExportBundle\EventListener\InvalidItemsCollector
    pim_import_export.archiver.invalid_item_csv_archiver.class:       Pim\Bundle\ImportExportBundle\Archiver\InvalidItemsCsvArchiver

services:
    pim_import_export.event_listener.archivist:
        class: %pim_import_export.event_listener.archivist.class%
        tags:
            - { name: kernel.event_subscriber }

    pim_import_export.event_listener.invalid_items_collector:
        class: %pim_import_export.event_listener.invalid_items_collector.class%
        tags:
            - { name: kernel.event_subscriber }

    pim_import_export.archiver.invalid_item_csv_archiver:
        class: %pim_import_export.archiver.invalid_item_csv_archiver.class%
        arguments:
            - '@pim_import_export.event_listener.invalid_items_collector'
            - '@pim_serializer.encoder.csv'
            - '@pim_archivist_filesystem'
        tags:
            - { name: pim_import_export.archiver }
