connector:
    name: Akeneo CSV Connector
    jobs:
        product_export:
            title: pim_import_export.jobs.product_export.title
            type:  export
            steps:
                export:
                    title:     pim_import_export.jobs.product_export.export.title
                    services:
                        reader:    pim_import_export.reader.orm.product
                        processor: pim_import_export.processor.csv_serializer.product
                        writer:    pim_import_export.writer.product_file
        product_import:
            title: pim_import_export.jobs.product_import.title
            type:  import
            steps:
                import:
                    title:     pim_import_export.jobs.product_import.import.title
                    services:
                        reader:    pim_import_export.reader.file.csv_product
                        processor: pim_import_export.processor.product
                        writer:    pim_import_export.writer.orm.product
                import_associations:
                    title:     pim_import_export.jobs.product_import.import_associations.title
                    services:
                        reader:    pim_import_export.reader.file.csv
                        processor: pim_import_export.processor.product_association
                        writer:    pim_import_export.writer.orm.product_association

