parameters:
    pim_import_export.reader.product.class:       Pim\Bundle\ImportExportBundle\Reader\ProductReader
    pim_import_export.reader.category.class:      Pim\Bundle\ImportExportBundle\Reader\CategoryReader
    pim_import_export.processor.serializer.class: Pim\Bundle\ImportExportBundle\Processor\SerializerProcessor
    pim_import_export.writer.file.class:          Pim\Bundle\ImportExportBundle\Writer\FileWriter

services:
    pim_import_export.reader.product:
        class: %pim_import_export.reader.product.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - @pim_config.manager.channel

    pim_import_export.reader.category:
        class: %pim_import_export.reader.category.class%
        arguments:
            - @doctrine.orm.default_entity_manager

    pim_import_export.processor.serializer:
        class: %pim_import_export.processor.serializer.class%
        arguments:
            - @pim_serializer

    pim_import_export.writer.file:
        class: %pim_import_export.writer.file.class%
