parameters:
    pim_import_export.reader.product.class:                         Pim\Bundle\ImportExportBundle\Reader\ORM\ProductReader
    pim_import_export.reader.entity.class:                          Pim\Bundle\ImportExportBundle\Reader\ORM\EntityReader
    
    pim_import_export.reader.csv.class:                             Pim\Bundle\ImportExportBundle\Reader\CsvReader
    pim_import_export.reader.product_csv.class:                     Pim\Bundle\ImportExportBundle\Reader\ProductCsvReader
    pim_import_export.reader.csv_file.class:                        Pim\Bundle\ImportExportBundle\Reader\CsvFileReader

    pim_import_export.processor.homogeneous_csv_serializer.class:   Pim\Bundle\ImportExportBundle\Processor\HomogeneousCsvSerializerProcessor
    pim_import_export.processor.heterogeneous_csv_serializer.class: Pim\Bundle\ImportExportBundle\Processor\HeterogeneousCsvSerializerProcessor
    pim_import_export.processor.valid_product_creation.class:       Pim\Bundle\ImportExportBundle\Processor\ValidProductCreationProcessor
    pim_import_export.processor.valid_category_creation.class:      Pim\Bundle\ImportExportBundle\Processor\ValidCategoryCreationProcessor
    pim_import_export.processor.product_csv_serializer.class:       Pim\Bundle\ImportExportBundle\Processor\ProductCsvSerializerProcessor
    pim_import_export.processor.valid_association_creation.class:   Pim\Bundle\ImportExportBundle\Processor\ValidAssociationCreationProcessor
    pim_import_export.processor.valid_group_creation.class:         Pim\Bundle\ImportExportBundle\Processor\ValidGroupCreationProcessor

    pim_import_export.writer.orm_product.class:                     Pim\Bundle\ImportExportBundle\Writer\OrmProductWriter
    pim_import_export.writer.orm_category.class:                    Pim\Bundle\ImportExportBundle\Writer\OrmCategoryWriter
    pim_import_export.writer.orm_association.class:                 Pim\Bundle\ImportExportBundle\Writer\OrmAssociationWriter
    pim_import_export.writer.orm_group.class:                       Pim\Bundle\ImportExportBundle\Writer\OrmGroupWriter

    pim_import_export.writer.file.class:                            Pim\Bundle\ImportExportBundle\Writer\FileWriter
    pim_import_export.writer.product_file.class:                    Pim\Bundle\ImportExportBundle\Writer\ProductFileWriter

    pim_import_export.reader.dummy.class:                           Pim\Bundle\ImportExportBundle\Reader\DummyReader
    pim_import_export.processor.dummy.class:                        Pim\Bundle\ImportExportBundle\Processor\DummyProcessor
    pim_import_export.writer.dummy.class:                           Pim\Bundle\ImportExportBundle\Writer\DummyWriter

services:

    # readers
    pim_import_export.reader.product:
        class: %pim_import_export.reader.product.class%
        arguments:
            - '@pim_catalog.manager.product'
            - '@pim_catalog.manager.channel'

    pim_import_export.reader.category:
        class: %pim_import_export.reader.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.category.class%

    pim_import_export.reader.attribute:
        class: %pim_import_export.reader.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.product_attribute.class%

    pim_import_export.reader.association:
        class: %pim_import_export.reader.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.association.class%

    pim_import_export.reader.group:
        class: %pim_import_export.reader.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.group.class%

    pim_import_export.reader.csv:
        class: %pim_import_export.reader.csv.class%

    pim_import_export.reader.csv_file:
        class: %pim_import_export.reader.csv_file.class%

    pim_import_export.reader.product_csv:
        class: %pim_import_export.reader.product_csv.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'

    pim_import_export.reader.dummy:
        class: %pim_import_export.reader.dummy.class%

    # processors
    pim_import_export.processor.homogeneous_csv_serializer:
        class: %pim_import_export.processor.homogeneous_csv_serializer.class%
        arguments:
            - '@pim_serializer'

    pim_import_export.processor.heterogeneous_csv_serializer:
        class: %pim_import_export.processor.heterogeneous_csv_serializer.class%
        arguments:
            - '@pim_serializer'

    pim_import_export.processor.product_csv_serializer:
        class: %pim_import_export.processor.product_csv_serializer.class%
        arguments:
            - '@pim_serializer'
            - '@pim_catalog.manager.channel'

    pim_import_export.processor.dummy:
        class: %pim_import_export.processor.dummy.class%

    pim_import_export.processor.valid_product_creation:
        class: %pim_import_export.processor.valid_product_creation.class%
        arguments:
            - '@pim_import_export.transformer.product'

    pim_import_export.processor.valid_category_creation:
        class: %pim_import_export.processor.valid_category_creation.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@validator'

    pim_import_export.processor.valid_association_creation:
        class: %pim_import_export.processor.valid_association_creation.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@validator'

    pim_import_export.processor.valid_group_creation:
        class: %pim_import_export.processor.valid_group_creation.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@validator'

    # writers
    pim_import_export.writer.file:
        class: %pim_import_export.writer.file.class%

    pim_import_export.writer.product_file:
        parent: pim_import_export.writer.file
        class: %pim_import_export.writer.product_file.class%
        arguments:
            - '@pim_catalog.manager.media'

    pim_import_export.writer.dummy:
        class: %pim_import_export.writer.dummy.class%

    pim_import_export.writer.orm_product:
        class: %pim_import_export.writer.orm_product.class%
        arguments:
            - '@pim_catalog.manager.product'
            - '@doctrine.orm.default_entity_manager'
            - '@pim_import_export.entity_cache'
            - '@pim_versioning.event_listener.addversion'

    pim_import_export.writer.orm_category:
        class: %pim_import_export.writer.orm_category.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'

    pim_import_export.writer.orm_association:
        class: %pim_import_export.writer.orm_association.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'

    pim_import_export.writer.orm_group:
        class: %pim_import_export.writer.orm_group.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
