datagrid:
    job-profile-grid:
        source:
            type: orm
            query:
                select:
                    - j.id
                    - j.code
                    - j.label
                    - j.alias as jobAlias
                    - j.status
                    - j.connector
                    - CONCAT('pim_import_export.status.', j.status) as jobStatus
                from:
                    - { table: OroBatchBundle:JobInstance, alias: j }
        columns:
            code:
                label: Code
            label:
                label: Label
            alias:
                label:     Job
                data_name: jobAlias
            connector:
                label: Connector
            status:
                label: Status
                type: translateable
                data_name: jobStatus
        properties:
            id: ~
            edit_link:
                type: url
                params:
                    - id
            delete_link:
                type: url
                params:
                    - id
            launch_link:
                type: url
                params:
                    - id
        actions:
            edit:
                type:      navigate
                label:     Edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete
                icon:  trash
                link:  delete_link
            launch:
                type:  navigate
                label: Launch
                icon:  play
                link:  launch_link
        sorters:
            columns:
                code:
                    data_name: j.code
                label:
                    data_name: j.label
                alias:
                    data_name: jobAlias
                connector:
                    data_name: j.connector
                status:
                    data_name: jobStatus
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                code:
                    type:      string
                    data_name: j.code
                label:
                    type:      string
                    data_name: j.label
                alias:
                    type:      string
                    data_name: jobAlias
                connector:
                    type:      string
                    data_name: j.connector
                status:
                    type:      choice
                    data_name: j.status
                    options:
                        field_options:
                            multiple: true
                            choices:
                                0: pim_import_export.status.0

    export-profile-grid:
        extend: job-profile-grid
        options:
            entityHint: export profile
        source:
            acl_resource: pim_importexport_export_profile_index
            query:
                where:
                    and:
                        - j.type = 'export'
        properties:
            edit_link:
                route: pim_importexport_export_profile_edit
            delete_link:
                route: pim_importexport_export_profile_remove
            launch_link:
                route: pim_importexport_export_profile_show

    import-profile-grid:
        extend: job-profile-grid
        options:
            entityHint: import profile
        source:
            acl_resource: pim_importexport_import_profile_index
            query:
                where:
                    and:
                        - j.type = 'import'
        properties:
            edit_link:
                route: pim_importexport_import_profile_edit
            delete_link:
                route: pim_importexport_import_profile_remove
            launch_link:
                route: pim_importexport_import_profile_show
