parameters:
    pim_import_export.form.type.import_entity.class:  Pim\Bundle\ImportExportBundle\Form\Type\ImportEntityType

services:
    pim_import_export.form.type.import_entity:
        class: '%pim_import_export.form.type.import_entity.class%'
        arguments:
            - '@pim_import_export.entity_cache'
        tags:
            - { name: form.type, alias: pim_import_entity }
