parameters:
    pim_import_export.form.type.product.class: Pim\Bundle\ImportExportBundle\Form\Type\ProductImportType

services:
    pim_import_export.form.type.product:
        class: '%pim_import_export.form.type.product.class%'
        arguments:
            - '@pim_catalog.form.transform_imported_product_data_subscriber'