parameters:
    pim_import_export.transformer.guesser.chained.class:       Pim\Bundle\ImportExportBundle\Transformer\Guesser\ChainedGuesser
    pim_import_export.transformer.guesser.type.class:          Pim\Bundle\ImportExportBundle\Transformer\Guesser\TypeGuesser
    pim_import_export.transformer.guesser.entity.class:        Pim\Bundle\ImportExportBundle\Transformer\Guesser\EntityGuesser
    pim_import_export.transformer.guesser.translation.class:   Pim\Bundle\ImportExportBundle\Transformer\Guesser\TranslationGuesser
    pim_import_export.transformer.guesser.default.class:       Pim\Bundle\ImportExportBundle\Transformer\Guesser\DefaultGuesser

services:
    pim_import_export.transformer.guesser:
        class: %pim_import_export.transformer.guesser.chained.class%

    pim_import_export.transformer.guesser.date:
        class: %pim_import_export.transformer.guesser.type.class%
        arguments:
            - '@pim_import_export.transformer.attribute.date'
            - date
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 150 }


    pim_import_export.transformer.guesser.datetime:
        class: %pim_import_export.transformer.guesser.type.class%
        arguments:
            - '@pim_import_export.transformer.attribute.date'
            - datetime
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 150 }


    pim_import_export.transformer.guesser.boolean:
        class: %pim_import_export.transformer.guesser.type.class%
        arguments:
            - '@pim_import_export.transformer.attribute.boolean'
            - boolean
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 150 }


    pim_import_export.transformer.guesser.translation:
        class: %pim_import_export.transformer.guesser.translation.class%
        arguments:
            - '@pim_import_export.transformer.property.translation'
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 140 }


    pim_import_export.transformer.guesser.entity:
        class: %pim_import_export.transformer.guesser.entity.class%
        arguments:
            - '@pim_import_export.transformer.property.entity'
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 150 }

    pim_import_export.transformer.guesser.default:
        class: %pim_import_export.transformer.guesser.default.class%
        arguments:
            - '@pim_import_export.transformer.property.default'
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 200 }
