connector:
    name: Akeneo CSV Connector
    jobs:
        product_export:
            title: pim_import_export.jobs.product_export.title
            type:  export
            steps:
                export:
                    title:     pim_import_export.jobs.product_export.export.title
                    reader:    pim_import_export.reader.orm.product
                    processor: pim_import_export.processor.csv_serializer.product
                    writer:    pim_import_export.writer.product_file
        category_export:
            title: pim_import_export.jobs.category_export.title
            type:  export
            steps:
                export:
                    title:     pim_import_export.jobs.category_export.export.title
                    reader:    pim_import_export.reader.orm.category
                    processor: pim_import_export.processor.csv_serializer.heterogeneous
                    writer:    pim_import_export.writer.file
        attribute_export:
            title: pim_import_export.jobs.attribute_export.title
            type:  export
            steps:
                export:
                    title:     pim_import_export.jobs.attribute_export.export.title
                    reader:    pim_import_export.reader.orm.attribute
                    processor: pim_import_export.processor.csv_serializer.heterogeneous
                    writer:    pim_import_export.writer.file
        attribute_option_export:
            title: pim_import_export.jobs.attribute_option_export.title
            type:  export
            steps:
                export:
                    title:     pim_import_export.jobs.attribute_option_export.export.title
                    reader:    pim_import_export.reader.orm.attribute_option
                    processor: pim_import_export.processor.csv_serializer.heterogeneous
                    writer:    pim_import_export.writer.file
        association_export:
            title: pim_import_export.jobs.association_export.title
            type:  export
            steps:
                export:
                    title:     pim_import_export.jobs.association_export.export.title
                    reader:    pim_import_export.reader.orm.association
                    processor: pim_import_export.processor.csv_serializer.homogeneous
                    writer:    pim_import_export.writer.file
        group_export:
            title: pim_import_export.jobs.group_export.title
            type:  export
            steps:
                export:
                    title:     pim_import_export.jobs.group_export.export.title
                    reader:    pim_import_export.reader.orm.group
                    processor: pim_import_export.processor.csv_serializer.homogeneous
                    writer:    pim_import_export.writer.file

        product_import:
            title: pim_import_export.jobs.product_import.title
            type:  import
            steps:
                import:
                    title:     pim_import_export.jobs.product_import.import.title
                    reader:    pim_import_export.reader.file.csv_product
                    processor: pim_import_export.processor.product
                    writer:    pim_import_export.writer.orm.product
        category_import:
            title: pim_import_export.jobs.category_import.title
            type:  import
            steps:
                import:
                    title:     pim_import_export.jobs.category_import.import.title
                    reader:    pim_import_export.reader.file.csv_category
                    processor: pim_import_export.processor.category
                    writer:    pim_import_export.writer.orm.category
        attribute_import:
            title: pim_import_export.jobs.attribute_import.title
            type:  import
            steps:
                import:
                    title:     pim_import_export.jobs.attribute_import.import.title
                    reader:    pim_import_export.reader.file.csv
                    processor: pim_import_export.processor.attribute
                    writer:    pim_import_export.writer.orm.attribute
        attribute_option_import:
            title: pim_import_export.jobs.attribute_option_import.title
            type:  import
            steps:
                import:
                    title:     pim_import_export.jobs.attribute_option_import.import.title
                    reader:    pim_import_export.reader.file.csv
                    processor: pim_import_export.processor.attribute_option
                    writer:    pim_import_export.writer.orm.attribute_option
        association_import:
            title: pim_import_export.jobs.association_import.title
            type: import
            steps:
                import:
                    title:     pim_import_export.jobs.association_import.import.title
                    reader:    pim_import_export.reader.file.csv
                    processor: pim_import_export.processor.association
                    writer:    pim_import_export.writer.orm.association
        group_import:
            title: pim_import_export.jobs.group_import.title
            type: import
            steps:
                import:
                    title:     pim_import_export.jobs.group_import.import.title
                    reader:    pim_import_export.reader.file.csv
                    processor: pim_import_export.processor.group
                    writer:    pim_import_export.writer.orm.group
