parameters:
    pim_import_export.processor.csv_serializer.homogeneous.class:   Pim\Bundle\ImportExportBundle\Processor\CsvSerializer\HomogeneousProcessor
    pim_import_export.processor.csv_serializer.heterogeneous.class: Pim\Bundle\ImportExportBundle\Processor\CsvSerializer\HeterogeneousProcessor
    pim_import_export.processor.csv_serializer.product.class:       Pim\Bundle\ImportExportBundle\Processor\CsvSerializer\ProductProcessor

    pim_import_export.processor.transformer.class:                  Pim\Bundle\ImportExportBundle\Processor\TransformerProcessor
    pim_import_export.processor.product.class:                      Pim\Bundle\ImportExportBundle\Processor\ProductProcessor
    pim_import_export.processor.category.class:                     Pim\Bundle\ImportExportBundle\Processor\CategoryProcessor
    pim_import_export.processor.attribute.class:                    Pim\Bundle\ImportExportBundle\Processor\AttributeProcessor
    pim_import_export.processor.product_association.class:          Pim\Bundle\ImportExportBundle\Processor\ProductAssociationProcessor
    pim_import_export.processor.nested_family.class:                Pim\Bundle\ImportExportBundle\Processor\NestedFamilyProcessor

    pim_import_export.processor.dummy.class:                        Pim\Bundle\ImportExportBundle\Processor\DummyProcessor

services:
    pim_import_export.processor.csv_serializer.homogeneous:
        class: %pim_import_export.processor.csv_serializer.homogeneous.class%
        arguments:
            - '@pim_serializer'

    pim_import_export.processor.csv_serializer.heterogeneous:
        class: %pim_import_export.processor.csv_serializer.heterogeneous.class%
        arguments:
            - '@pim_serializer'

    pim_import_export.processor.csv_serializer.product:
        class: %pim_import_export.processor.csv_serializer.product.class%
        arguments:
            - '@pim_serializer'
            - '@pim_catalog.manager.channel'

    pim_import_export.processor.dummy:
        class: %pim_import_export.processor.dummy.class%

    pim_import_export.processor.transformer:
        class: %pim_import_export.processor.transformer.class%
        abstract: true
        arguments:
            - '@pim_import_export.validator.import'
            - '@translator'
            - '@pim_import_export.transformer.orm'

    pim_import_export.processor.channel:
        parent: pim_import_export.processor.transformer
        arguments:
            - '%pim_catalog.entity.channel.class%'
        calls:
            - [ addMapping, [ tree, category ] ]

    pim_import_export.processor.group_type:
        parent: pim_import_export.processor.transformer
        arguments:
            - '%pim_catalog.entity.group_type.class%'

    pim_import_export.processor.product:
        class: %pim_import_export.processor.product.class%
        arguments:
            - '@pim_import_export.validator.product_import'
            - '@translator'
            - '@pim_import_export.transformer.product'

    pim_import_export.processor.product_association:
        class: %pim_import_export.processor.product_association.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@validator'
            - '@pim_catalog.manager.product'

    pim_import_export.processor.category:
        class: %pim_import_export.processor.category.class%
        arguments:
            - '@pim_import_export.validator.import'
            - '@translator'
            - '@pim_import_export.transformer.orm'
            - '@pim_import_export.entity_cache'
            - '%pim_catalog.entity.category.class%'

    pim_import_export.processor.association_type:
        parent: pim_import_export.processor.transformer
        arguments:
            - '%pim_catalog.entity.association_type.class%'

    pim_import_export.processor.group:
        parent: pim_import_export.processor.transformer
        arguments:
            - '%pim_catalog.entity.group.class%'

    pim_import_export.processor.attribute_group:
        parent: pim_import_export.processor.transformer
        arguments:
            - '%pim_catalog.entity.attribute_group.class%'

    pim_import_export.processor.attribute:
        class: %pim_import_export.processor.transformer.class%
        arguments:
            - '@pim_import_export.validator.import'
            - '@translator'
            - '@pim_import_export.transformer.attribute'
            - '%pim_catalog.entity.product_attribute.class%'

    pim_import_export.processor.attribute_option:
        parent: pim_import_export.processor.transformer
        arguments:
            - '%pim_catalog.entity.product_attribute_option.class%'

    pim_import_export.processor.family:
        class: %pim_import_export.processor.transformer.class%
        arguments:
            - '@pim_import_export.validator.import'
            - '@translator'
            - '@pim_import_export.transformer.family'
            - '%pim_catalog.entity.family.class%'

    pim_import_export.processor.job_instance:
        class: %pim_import_export.processor.transformer.class%
        arguments:
            - '@pim_import_export.validator.job_instance_import'
            - '@translator'
            - '@pim_import_export.transformer.job_instance'
            - '%pim_catalog.entity.job_instance.class%'
        calls:
            - [ addMapping, [ configuration, rawConfiguration ] ]
