parameters:
    pim_serializer.class:                            Symfony\Component\Serializer\Serializer
    pim_serializer.encoder.xml.class:                Symfony\Component\Serializer\Encoder\XmlEncoder
    pim_serializer.encoder.json.class:               Symfony\Component\Serializer\Encoder\JsonEncoder
    pim_serializer.normalizer.product.class:         Pim\Bundle\ImportExportBundle\Normalizer\ProductNormalizer
    pim_serializer.normalizer.get_set_method.class:  Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer

services:
    pim_serializer:
        class: %pim_serializer.class%

    pim_serializer.encoder.xml:
        public: false
        class: %pim_serializer.encoder.xml.class%
        tags:
            - { name: pim_serializer.encoder }

    pim_serializer.encoder.json:
        public: false
        class: %pim_serializer.encoder.json.class%
        tags:
            - { name: pim_serializer.encoder }

    pim_serializer.normalizer.product:
        class: %pim_serializer.normalizer.product.class%
        arguments:
            - @router
        tags:
            - { name: pim_serializer.normalizer }

    pim_serializer.normalizer.get_set_method:
        public: false
        class: %pim_serializer.normalizer.get_set_method.class%
        tags:
            - { name: pim_serializer.normalizer }
