parameters:
    pim_import_export.transformer.orm.class:                         Pim\Bundle\ImportExportBundle\Transformer\ORMTransformer
    pim_import_export.transformer.product.class:                     Pim\Bundle\ImportExportBundle\Transformer\ORMProductTransformer
    pim_import_export.transformer.family.class:                      Pim\Bundle\ImportExportBundle\Transformer\ORMFamilyTransformer
    pim_import_export.transformer.attribute.class:                   Pim\Bundle\ImportExportBundle\Transformer\ORMAttributeTransformer
    pim_import_export.transformer.job_instance.class:                Pim\Bundle\ImportExportBundle\Transformer\ORMJobInstanceTransformer
    pim_import_export.transformer.property.translation.class:        Pim\Bundle\ImportExportBundle\Transformer\Property\TranslationTransformer
    pim_import_export.transformer.property.nested_translation.class: Pim\Bundle\ImportExportBundle\Transformer\Property\NestedTranslationTransformer
    pim_import_export.transformer.property.default.class:            Pim\Bundle\ImportExportBundle\Transformer\Property\DefaultTransformer
    pim_import_export.transformer.property.entity.class:             Pim\Bundle\ImportExportBundle\Transformer\Property\EntityTransformer
    pim_import_export.transformer.property.media.class:              Pim\Bundle\ImportExportBundle\Transformer\Property\MediaTransformer
    pim_import_export.transformer.property.date.class:               Pim\Bundle\ImportExportBundle\Transformer\Property\DateTransformer
    pim_import_export.transformer.property.boolean.class:            Pim\Bundle\ImportExportBundle\Transformer\Property\BooleanTransformer
    pim_import_export.transformer.property.metric.class:             Pim\Bundle\ImportExportBundle\Transformer\Property\MetricTransformer
    pim_import_export.transformer.property.prices.class:             Pim\Bundle\ImportExportBundle\Transformer\Property\PricesTransformer
    pim_import_export.transformer.property.skip.class:               Pim\Bundle\ImportExportBundle\Transformer\Property\SkipTransformer
    pim_import_export.transformer.column_info_transformer.class:     Pim\Bundle\ImportExportBundle\Transformer\ColumnInfo\ColumnInfoTransformer
    pim_import_export.transformer.column_info.class:                 Pim\Bundle\ImportExportBundle\Transformer\ColumnInfo\ColumnInfo

services:
    pim_import_export.transformer.orm:
        class: %pim_import_export.transformer.orm.class%
        arguments:
            - '@doctrine'
            - '@property_accessor'
            - '@pim_import_export.transformer.guesser'
            - '@pim_import_export.transformer.column_info_transformer'

    pim_import_export.transformer.product:
        class: %pim_import_export.transformer.product.class%
        parent: pim_import_export.transformer.orm
        arguments:
            - '@pim_catalog.manager.product'
            - '@pim_import_export.attribute_cache'
            - '@pim_import_export.reader.cached_association'

    pim_import_export.transformer.attribute:
        class: %pim_import_export.transformer.attribute.class%
        parent: pim_import_export.transformer.orm
        arguments:
            - '@pim_catalog.manager.attribute'
            - '@pim_import_export.entity_cache'

    pim_import_export.transformer.family:
        class: %pim_import_export.transformer.family.class%
        parent: pim_import_export.transformer.orm
        arguments:
            - '@pim_catalog.factory.family'
            - %pim_catalog.entity.family.class%
            - %pim_catalog.entity.attribute_requirement.class%

    pim_import_export.transformer.job_instance:
        class: %pim_import_export.transformer.job_instance.class%
        parent: pim_import_export.transformer.orm

    pim_import_export.transformer.column_info_transformer:
        class: %pim_import_export.transformer.column_info_transformer.class%
        arguments:
            - %pim_import_export.transformer.column_info.class%

    pim_import_export.transformer.property.translation:
        class: %pim_import_export.transformer.property.translation.class%
        arguments:
            - '@property_accessor'

    pim_import_export.transformer.property.nested_translation:
        class: %pim_import_export.transformer.property.nested_translation.class%
        arguments:
            - '@property_accessor'

    pim_import_export.transformer.property.default:
        class: %pim_import_export.transformer.property.default.class%
        public: false
        tags:
            - name: pim_import_export.transformer.product.attribute
              backend_type: default

    pim_import_export.transformer.property.entity:
        class: %pim_import_export.transformer.property.entity.class%
        arguments:
            - '@pim_import_export.entity_cache'
        public: false

    pim_import_export.transformer.property.media:
        class: %pim_import_export.transformer.property.media.class%
        public: false
        tags:
            - name: pim_import_export.transformer.product.attribute
              backend_type: media

    pim_import_export.transformer.property.prices:
        class: %pim_import_export.transformer.property.prices.class%
        public: false
        arguments:
            - '@pim_catalog.manager.currency'

    pim_import_export.transformer.property.metric:
        class: %pim_import_export.transformer.property.metric.class%
        public: false

    pim_import_export.transformer.property.date:
        class: %pim_import_export.transformer.property.date.class%
        public: false

    pim_import_export.transformer.property.boolean:
        class: %pim_import_export.transformer.property.boolean.class%
        public: false

    pim_import_export.transformer.property.skip:
        class: %pim_import_export.transformer.property.skip.class%
        public: false
