Pim\Bundle\CatalogBundle\Entity\Locale:
    type: entity
    table: pim_catalog_locale
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\LocaleRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 20
            unique: true
        fallback:
            type: string
            length: 20
            nullable: true
        activated:
            type: boolean
            column: is_activated
    manyToOne:
        defaultCurrency:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Currency
            inversedBy: locales
            joinColumns:
                default_currency_id:
                    referencedColumnName: id
    manyToMany:
        channels:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Channel
            mappedBy: locales
