Pim\Bundle\CatalogBundle\Entity\ProductAttributeTranslation:
    type: entity
    table: pim_catalog_attribute_translation
    uniqueConstraints:
        locale_foreign_key_idx:
            columns:
                - locale
                - foreign_key
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        label:
            type: string
            length: 64
        locale:
            type: string
            scale: 0
            length: 20
    manyToOne:
        foreignKey:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\ProductAttribute
            inversedBy: translations
            joinColumns:
                foreign_key:
                    referencedColumnName: id
                    onDelete: CASCADE
