pim_catalog_batch_operation_choose:
    path: /choose
    defaults: { _controller: pim_catalog.controller.batch_operation:chooseAction }
    requirements:
        _method: GET|POST

pim_catalog_batch_operation_configure:
    path: /{operationAlias}/configure
    defaults: { _controller: pim_catalog.controller.batch_operation:configureAction }
    requirements:
        _method: GET|POST

pim_catalog_batch_operation_perform:
    path: /{operationAlias}/perform
    defaults: { _controller: pim_catalog.controller.batch_operation:performAction }
    requirements:
        _method: POST
