attributes_config:
    pim_product_price_collection:
        name: 'Prices'
        properties: [ 'numberMin', 'numberMax', 'decimalsAllowed', 'negativeAllowed', 'searchable' ]
        parameters: [ 'translatable', 'availableLocales' ]
