services:
    pim_product.attributetype.textarea:
        class: Pim\Bundle\ProductBundle\AttributeType\TextAreaType
        arguments: ["text", "textarea"]
        tags:
            - { name: oro_flexibleentity.attributetype, alias: pim_product_textarea }
    pim_product.attributetype.multiselect:
        class: Pim\Bundle\ProductBundle\AttributeType\OptionMultiSelectType
        arguments: ["options", "entity"]
        tags:
            - { name: oro_flexibleentity.attributetype, alias: pim_product_multiselect }
    pim_product.attributetype.simpleselect:
        class: Pim\Bundle\ProductBundle\AttributeType\OptionSimpleSelectType
        arguments: ["option", "entity"]
        tags:
            - { name: oro_flexibleentity.attributetype, alias: pim_product_simpleselect }
    pim_product.attributetype.price:
        class: Pim\Bundle\ProductBundle\AttributeType\PriceType
        arguments: ["prices", "entity", @pim_config.manager.locale]
        tags:
            - { name: oro_flexibleentity.attributetype, alias: pim_product_price }