services:
    pim_product.attributetype.multiselect:
        class: Pim\Bundle\ProductBundle\AttributeType\OptionMultiSelectType
        arguments: ["@translator"]
        tags:
            - { name: oro_flexibleentity.attributetype, alias: pim_product_multiselect }
    pim_product.attributetype.simpleselect:
        class: Pim\Bundle\ProductBundle\AttributeType\OptionSimpleSelectType
        arguments: ["@translator"]
        tags:
            - { name: oro_flexibleentity.attributetype, alias: pim_product_simpleselect }
