parameters:
    pim_product.productattribute_grid_manager_class:  Pim\Bundle\ProductBundle\Datagrid\AttributeDatagridManager
    pim_product.product_grid_manager_class:           Pim\Bundle\ProductBundle\Datagrid\ProductDatagridManager
    oro_grid.datagrid.class:       Pim\Bundle\ProductBundle\Datagrid\ProductDatagrid

services:
    # Product attribute grid manager
    pim_product.productattribute_grid_manager:
        class: "%pim_product.productattribute_grid_manager_class%"
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: attributes
              entity_hint: attributes
              route_name: pim_product_productattribute_index

    # Product grid manager
    pim_product.product_grid_manager:
        class: "%pim_product.product_grid_manager_class%"
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: products
              entity_name: Pim\Bundle\ProductBundle\Entity\Product
              entity_hint: products
              flexible: true
              route_name: pim_product_product_index
        calls:
            - [ setLocaleManager, [@pim_config.manager.locale] ]
            - [ setChannelManager, [@pim_config.manager.channel] ]
