entities_config:
    Pim\Bundle\ProductBundle\Entity\Product:
        flexible_manager:         product_manager
        flexible_class:           Pim\Bundle\ProductBundle\Entity\Product
        flexible_value_class:     Pim\Bundle\ProductBundle\Entity\ProductValue
        attribute_extended_class: Pim\Bundle\ProductBundle\Entity\ProductAttribute
        flexible_init_mode:       required_attributes
