services:
    pim_filter.form.type.filter.locale:
        class:     Pim\Bundle\ProductBundle\Form\Type\Filter\LocaleFilterType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: pim_type_locale_filter }
