oro_menu_config:
    items:
        pim_enrich_tab:
            label: 'Enrich'
            uri: '#'
        pim_enrich_product:
            label: 'Products'
            route: 'pim_product_product_index'
        pim_enrich_attribute:
            label: 'Attributes'
            route: 'pim_product_productattribute_index'
        pim_enrich_family:
            label: 'Families'
            route: 'pim_product_productfamily_index'
        pim_enrich_attributegroup:
            label: 'Groups'
            route: 'pim_product_attributegroup_index'

    tree:
        application_menu:
            children:
                pim_enrich_tab:
                    children:
                        pim_enrich_product: ~
                        pim_enrich_family: ~
                        pim_enrich_attribute: ~
                        pim_enrich_attributegroup: ~