'attributes':
    'sku':
        'labels':
            'default': 'SKU'
            'fr_FR':   'SKU'
        'type': 'pim_product_text'
        'description': 'the product sku'
        'group': 'general'
        'parameters':
            'required': true
            'unique': true
            'useableAsGridColumn': true
            'useableAsGridFilter': true
            'sortOrder': 1
    'name':
        'labels':
            'default': 'Name'
            'fr_FR':   'Nom'
        'type': 'pim_product_text'
        'description': 'the product name'
        'group': 'general'
        'parameters':
            'translatable': true
            'useableAsGridColumn': true
            'useableAsGridFilter': true
            'sortOrder': 2
    'price':
        'labels':
            'default': 'Price'
            'fr_FR':   'Prix'
        'type': 'pim_product_price_collection'
        'description': 'the product price'
        'group': 'marketing'
        'parameters':
            'useableAsGridColumn': true
            'useableAsGridFilter': true
            'numberMin': 1
            'numberMax': 500
            'sortOrder': 1
    'short_description':
        'labels':
            'default': 'Short Description'
            'fr_FR':   'Description courte'
        'type': 'pim_product_textarea'
        'description': 'the product short description'
        'group': 'general'
        'parameters':
            'translatable': true
            'scopable': true
            'useableAsGridColumn': true
            'useableAsGridFilter': true
            'maxCharacters': 100
            'sortOrder': 3
    'long_description':
        'labels':
            'default': 'Long Description'
            'fr_FR':   'Description longue'
        'type': 'pim_product_textarea'
        'description': 'the product long description'
        'group': 'general'
        'parameters':
            'translatable': true
            'scopable': true
            'useableAsGridColumn': true
            'useableAsGridFilter': true
            'wysiwygEnabled': true
            'sortOrder': 4
    'release_date':
        'labels':
            'default': 'Release date'
            'fr_FR':   'Date de sortie'
        'type': 'pim_product_date'
        'description': 'the product date'
        'group': 'general'
        'parameters':
            'useableAsGridColumn': true
            'useableAsGridFilter': true
            'dateMin': '2012-01-01'
            'dateMax': '2014-01-01'
            'sortOrder': 5
    'file_upload':
        'labels':
            'default': 'File upload'
            'fr_FR':   'Fichier téléchargé'
        'type': 'pim_product_file'
        'description': 'File upload'
        'group': 'seo'
        'parameters':
            'maxFileSize': '2000'
            'sortOrder': 1
    'image_upload':
        'labels':
            'default': 'Image upload'
            'fr_FR':   'Image téléchargée'
        'type': 'pim_product_image'
        'description': 'File upload'
        'group': 'seo'
        'parameters':
            'sortOrder': 2
    'size':
        'labels':
            'default': 'Size'
            'fr_FR':   'Taille'
        'type': 'pim_product_simpleselect'
        'description': 'Size'
        'group': 'sizes'
        'parameters':
            'useableAsGridColumn': true
            'useableAsGridFilter': true
            'sortOrder': 1
            'defaultValue': 'M'
        'options':
            'XS':
                labels:
                    'default': 'XS'
                    'en_US': 'XS'
            'S':
                labels:
                    'default': 'S'
                    'en_US': 'S'
            'M':
                labels:
                    'default': 'M'
                    'en_US': 'M'
            'L':
                labels:
                    'default': 'L'
                    'en_US': 'L'
            'XL':
                labels:
                    'default': 'XL'
                    'en_US': 'XL'
    'color':
        'labels':
            'default': 'Color'
            'fr_FR':   'Couleur'
        'type': 'pim_product_multiselect'
        'description': 'Couleur'
        'group': 'colors'
        'parameters':
            'useableAsGridColumn': true
            'useableAsGridFilter': true
            'sortOrder': 1
        'options':
            'Red':
                labels:
                    'default': 'Red'
                    'en_US': 'Red'
                    'fr_FR': 'Rouge'
            'Blue':
                labels:
                    'default': 'Blue'
                    'en_US': 'Blue'
                    'fr_FR': 'Bleu'
            'Green':
                labels:
                    'default': 'Green'
                    'en_US': 'Green'
                    'fr_FR': 'Vert'
            'Purple':
                'labels':
                    'default': 'Purple'
                    'en_US': 'Purple'
                    'fr_FR': 'Violet'
            'Orange':
                'labels':
                    'default': 'Orange'
                    'en_US': 'Orange'
                    'fr_FR': 'Orange'
    'manufacturer':
        'labels':
            'default': 'Manufacturer'
            'fr_FR':   'Fabriquant'
        'type': 'pim_product_simpleselect'
        'description': 'Manufacturer'
        'group': 'general'
        'parameters':
            'useableAsGridColumn': true
            'useableAsGridFilter': true
            'sortOrder': 10
        'options':
            'MyMug':
                labels:
                    'default': 'MyMug'
                    'en_US': 'MyMug'
            'MugStore':
                labels:
                    'default': 'MugStore'
                    'en_US': 'MugStore'

