variant_groups:
    AKENEO_MUG:
        labels:
            en_US: Akeneo Mug
            fr_FR: Tasse Akeneo
        attributes:
            - unique_color
    AKENEO_TSHIRT:
        labels:
            en_US: Akeneo T-Shirt
            fr_FR: T-Shirt Akeneo
        attributes:
            - unique_color
            - size
    ORO_TSHIRT:
        labels:
            en_US: Oro T-Shirt
            fr_FR: T-Shirt Oro
        attributes:
            - size
