groups:
    AKENEO_MUG:
        type: VARIANT
        labels:
            en_US: Akeneo Mug
            fr_FR: Tasse Akeneo
        attributes:
            - unique_color
    AKENEO_TSHIRT:
        type: VARIANT
        labels:
            en_US: Akeneo T-Shirt
            fr_FR: T-Shirt Akeneo
        attributes:
            - unique_color
            - size
    ORO_TSHIRT:
        type: VARIANT
        labels:
            en_US: Oro T-Shirt
            fr_FR: T-Shirt Oro
        attributes:
            - size
    AKENEO_XSELL:
        type: X_SELL
        labels:
            en_US: Akeneo X-sell
            fr_FR: Akeneo X-sell
