'families':
    'mug':
        'labels':
            'en_US': 'Mug'
            'fr_FR': 'Tasse'
        'attributes' :
            - 'name'
            - 'short_description'
            - 'manufacturer'
            - 'color'
        'attributeAsLabel': 'name'
    'shirt':
        'labels':
            'en_US': 'Shirt'
            'fr_FR': 'Chemise'
        'attributes' :
            - 'name'
            - 'short_description'
            - 'size'
            - 'color'
        'attributeAsLabel': 'name'
    'shoe':
        'labels':
            'en_US': 'Shoe'
            'fr_FR': 'Chaussure'
        'attributes' :
            - 'name'
            - 'short_description'
            - 'long_description'
            - 'size'
            - 'color'
            - 'image_upload'
        'attributeAsLabel': 'name'
