channels:
    'ecommerce':
        'code':  'ecommerce'
        'label': 'E-Commerce'
        'locales':
            - 'en_US'
            - 'fr_FR'
    'mobile':
        'code':  'mobile'
        'label': 'Mobile'
        'locales':
            - 'en_US'
            - 'fr_FR'
