parameters:
    product_manager_class:              Pim\Bundle\ProductBundle\Manager\ProductManager
    product_entity_class:               Pim\Bundle\ProductBundle\Entity\Product

    simple_product_handler_class:       Pim\Bundle\ProductBundle\Form\Handler\SimpleProductHandler

    product_attribute_class:            Pim\Bundle\ProductBundle\Entity\ProductAttribute
    product_attribute_value_class:      Pim\Bundle\ProductBundle\Entity\ProductValue

    product_attribute_type_class:       Pim\Bundle\ProductBundle\Form\Type\ProductAttributeType
    product_attribute_handler_class:    Pim\Bundle\ProductBundle\Form\Handler\ProductAttributeHandler
    product_attribute_subscriber_class: Pim\Bundle\ProductBundle\Form\Subscriber\ProductAttributeSubscriber

    attribute_group_entity_class:       Pim\Bundle\ProductBundle\Entity\AttributeGroup
    attribute_group_handler_class:      Pim\Bundle\ProductBundle\Form\Handler\AttributeGroupHandler
    attribute_group_type_class:         Pim\Bundle\ProductBundle\Form\Type\AttributeGroupType

    export_profile_entity_class:        Pim\Bundle\ProductBundle\Entity\ExportProfile
    export_profile_handler_class:       Pim\Bundle\ProductBundle\Form\Handler\ExportProfileHandler
    export_profile_type_class:          Pim\Bundle\ProductBundle\Form\Type\ExportProfileType

    metric_attribute_validator_class:   Pim\Bundle\ProductBundle\Validator\Constraints\ValidMetricAttributeValidator

    pim_product.attributes_config:      ~
    pim_product.segment_class:          Pim\Bundle\ProductBundle\Entity\ProductSegment
    pim_product.segment_manager_class:  Pim\Bundle\ProductBundle\Manager\ProductSegmentManager

services:
    # Managers
    product_manager:
        class:     %product_manager_class%
        arguments:
            - %product_entity_class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @oro_flexibleentity.attributetype.factory
            - @pim_media_manager
        tags:
            - { name: oro_flexibleentity_manager, entity: %product_entity_class%}
        calls:
            - [ addAttributeType, ['oro_flexibleentity_text'] ]
            - [ addAttributeType, ['pim_product_textarea'] ]
            - [ addAttributeType, ['oro_flexibleentity_number'] ]
            - [ addAttributeType, ['oro_flexibleentity_money'] ]
            - [ addAttributeType, ['pim_product_multiselect'] ]
            - [ addAttributeType, ['pim_product_simpleselect'] ]
            - [ addAttributeType, ['oro_flexibleentity_file'] ]
            - [ addAttributeType, ['oro_flexibleentity_image'] ]
            - [ addAttributeType, ['oro_flexibleentity_metric'] ]
            - [ addAttributeType, ['oro_flexibleentity_boolean'] ]
            - [ addAttributeType, ['oro_flexibleentity_date'] ]

    pim_product.classification_tree_manager:
        class:     %pim_product.segment_manager_class%
        arguments: [@doctrine.orm.entity_manager, %pim_product.segment_class%]

    # Form
    pim_product.form.simple_product:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments: ["pim_simple_product_form", "pim_simple_product"]

    pim_product.form.attribute:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments: ["pim_product_attribute_form", "pim_product_attribute"]

    pim_product.form.attribute_group:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments: ["pim_attribute_group_form", "pim_attribute_group"]

    pim_product.form.export_profile:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments: ["pim_export_profile_form", "pim_export_profile"]

    # Types
    pim_product.form.type.product:
        class: Pim\Bundle\ProductBundle\Form\Type\ProductType
        arguments: [@product_manager, 'pim_product_value']
        tags:
            - { name: form.type, alias: pim_product }

    pim_product.form.type.simple_product:
        class: Pim\Bundle\ProductBundle\Form\Type\SimpleProductType
        arguments: [@product_manager, 'pim_product_value']
        tags:
            - { name: form.type, alias: pim_simple_product }

    pim_product.form.type.product_value:
        class: Pim\Bundle\ProductBundle\Form\Type\ProductValueType
        arguments: [@product_manager]
        tags:
            - { name: form.type, alias: pim_product_value }

    pim_product.form.type.attribute:
        class: %product_attribute_type_class%
        tags:
            - { name: form.type, alias: pim_product_attribute }
        arguments: [@pim_product.attribute_service, @pim_product.form.subscriber.attribute]

    pim_product.form.type.attribute_group:
        class: %attribute_group_type_class%
        tags:
            - { name: form.type, alias: pim_attribute_group }

    pim_product.form.type.export_profile:
        class: %export_profile_type_class%
        tags:
            - { name: form.type, alias: pim_export_profile }

    pim_product.form.type.wysiwyg:
        class: Pim\Bundle\ProductBundle\Form\Type\WysiwygType
        tags:
            - { name: form.type, alias: pim_wysiwyg }

    # Handlers
    pim_product.form.handler.simple_product:
        class: %simple_product_handler_class%
        scope: request
        arguments: [@pim_product.form.simple_product, @request, @product_manager]

    pim_product.form.handler.attribute:
        class: %product_attribute_handler_class%
        scope: request
        arguments: [@pim_product.form.attribute, @request, @doctrine.orm.entity_manager, @pim_product.attribute_service]

    pim_product.form.handler.attribute_group:
        class: %attribute_group_handler_class%
        scope: request
        arguments: [@pim_product.form.attribute_group, @request, @doctrine.orm.entity_manager]

    pim_product.form.handler.export_profile:
        class: %export_profile_handler_class%
        scope: request
        arguments: [@pim_product.form.export_profile, @request, @doctrine.orm.entity_manager]

    # Subscribers
    pim_product.form.subscriber.attribute:
        class: %product_attribute_subscriber_class%
        arguments: [@pim_product.attribute_service]

    # Validators
    pim_product.form.validator.metric_attribute:
        class: %metric_attribute_validator_class%
        arguments: [%oro_measure.measures_config%]
        tags:
        - { name: validator.constraint_validator, alias: pim_metric_attribute_validator }

    # Media
    pim_media_manager:
        class: Pim\Bundle\ProductBundle\Manager\MediaManager
        arguments: [@knp_gaufrette.filesystem_map, "pim", %upload_dir%]

    # Attribute manager
    pim_product.attribute_service:
        class: Pim\Bundle\ProductBundle\Service\AttributeService
        arguments: [%pim_product.attributes_config%, @product_manager, @pim_config.manager.locale, @oro_flexibleentity.attributetype.factory]
