parameters:
    product_manager_class:         Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    product_entity_class:          Pim\Bundle\ProductBundle\Entity\Product
    
    product_attribute_class:       Pim\Bundle\ProductBundle\Entity\ProductAttribute
    product_attribute_value_class: Pim\Bundle\ProductBundle\Entity\ProductValue
    
    product_attribute_type_class:  Pim\Bundle\ProductBundle\Form\Type\ProductAttributeType
    product_attribute_handler_class: Pim\Bundle\ProductBundle\Form\Handler\ProductAttributeHandler

services:
    # Managers
    product_manager:
        class:     "%product_manager_class%"
        arguments: [%product_entity_class%, %oro_flexibleentity.flexible_config%, "@doctrine.orm.entity_manager", "@event_dispatcher"]
        
    
    # Form
    pim_product.form.attribute:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["pim_product_attribute_form", "pim_product_attribute"]
            
    pim_product.form.type.attribute:
        class:  %product_attribute_type_class%
        tags:
            - { name: form.type, alias: pim_product_attribute }
    
    # Handlers
    pim_product.form.handler.attribute:
        class:  %product_attribute_handler_class%
        scope: request
        arguments: ["@pim_product.form.attribute", "@request", "@doctrine.orm.entity_manager"]
        