parameters:
    pim_translation.translatable_field_class: Pim\Bundle\TranslationBundle\Form\Type\TranslatedFieldType

services:
    pim_translation.form.type.translatable_field:
        class: %pim_translation.translatable_field_class%
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: pim_translatable_field }
