Pim\Bundle\ProductBundle\Entity\ProductAttribute:
    constraints:
        - Callback:
            methods: 
                - [Pim\Bundle\ProductBundle\Validator\ProductAttributeValidator, isValid]
            