filter:
    paths:
        - src/*
    excluded_paths:
        - src/Pim/Bundle/JsFormValidationBundle/Generator/*
        - src/Pim/Bundle/*/Tests/

tools:
    php_mess_detector:
        filter:
            paths:
                - src/*
            excluded_paths:
                - src/Pim/Bundle/JsFormValidationBundle/Generator/*
                - src/Pim/Bundle/*/Tests/
    php_cs_fixer:
        config:
            level: all
    php_analyzer:
        filter:
            paths:
                - src/*
            excluded_paths:
                - src/Pim/Bundle/JsFormValidationBundle/Generator/*
                - src/Pim/Bundle/*/Tests/
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths:
                - src/*
            excluded_paths:
                - src/Pim/Bundle/JsFormValidationBundle/Generator/*
                - src/Pim/Bundle/*/Tests/
    sensiolabs_security_checker: true
    php_cpd:
        filter:
            paths:
                - src/*
            excluded_paths:
                - src/Pim/Bundle/JsFormValidationBundle/Generator/*
                - src/Pim/Bundle/*/Tests/
    php_loc:
        excluded_dirs:
            - app/
            - features/
            - src/Pim/Bundle/*/Tests/
            - src/Pim/Bundle/JsFormValidationBundle/Generator/*
            - vendor/
            - web/
    php_pdepend:
        excluded_dirs:
            - app/
            - features/
            - src/Pim/Bundle/*/Tests/
            - src/Pim/Bundle/JsFormValidationBundle/Generator/*
            - vendor/
            - web/
