versionable:
    - Pim\Bundle\CatalogBundle\Model\Product
    - Pim\Bundle\CatalogBundle\Model\Group
    - Pim\Bundle\CatalogBundle\Model\Category
    - Pim\Bundle\CatalogBundle\Entity\Family
    - Pim\Bundle\CatalogBundle\Entity\Association
    - Pim\Bundle\CatalogBundle\Entity\ProductAttribute
    - Pim\Bundle\CatalogBundle\Entity\AttributeGroup
    - Pim\Bundle\CatalogBundle\Entity\Channel
    - Oro\Bundle\BatchBundle\Entity\JobInstance
