datagrid:
    association-grid:
        options:
            entityHint: association
        source:
            acl_resource: pim_catalog_association_index
            type: pim_orm
            entity: %pim_catalog.entity.association.class%
        columns:
            code:
                label: Code
            label:
                label: Label
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_catalog_association_edit
                params:
                    - id
            delete_link:
                type: url
                route: pim_catalog_association_remove
                params:
                    - id
        actions:
            edit:
                type:      navigate
                label:     Edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete
                icon:  trash
                link:  delete_link
        sorters:
            columns:
                code:
                    data_name: a.code
                label:
                    data_name: label
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: a.code
                label:
                    type: string
                    label: Label
                    data_name: translation.label
    attribute-grid:
        options:
            entityHint: attribute
        source:
            acl_resource: pim_catalog_attribute_index
            type: pim_orm
            entity: %pim_catalog.entity.product_attribute.class%
        columns:
            code:
                label: Code
            label:
                label: Label
            attributeType:
                label: Type
            scopable:
                label:         Scopable
                frontend_type: boolean
            translatable:
                label:         Localizable
                frontend_type: boolean
            group:
                label:     Group
                data_name: groupLabel
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_catalog_productattribute_edit
                params:
                    - id
            delete_link:
                type: url
                route: pim_catalog_productattribute_remove
                params:
                    - id
        actions:
            edit:
                type:      navigate
                label:     Edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete
                icon:  trash
                link:  delete_link
        sorters:
            columns:
                code:
                    data_name: a.code
                label:
                    data_name: label
                scopable:
                    data_name: a.scopable
                translatable:
                    data_name: a.translatable
                group:
                    data_name: groupLabel
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: a.code
                label:
                    type:      string
                    label:     Label
                    data_name: translation.label
                attributeType:
                    type:      choice
                    data_name: a.attributeType
                    options:
                        field_options:
                            choices: @pim_catalog.manager.product_attribute->getAttributeTypes
                scopable:
                    type:      boolean
                    data_name: a.scopable
                translatable:
                    type:      boolean
                    data_name: a.translatable
                group:
                    type:      choice
                    data_name: attributeGroup.code
                    options:
                        field_options:
                            choices: @pim_catalog.manager.product_attribute->getAttributeGroupChoices

    channel-grid:
        options:
            entityHint: channel
        source:
            acl_resource: pim_catalog_channel_index
            type: orm
            query:
                select:
                    - c.id
                    - c.code
                    - c.label
                    - >
                        (CASE WHEN ct.label IS NULL THEN
                            category.code
                        ELSE
                            ct.label
                        END) AS categoryLabel
                from:
                    - { table: PimCatalogBundle:Channel, alias: c }
                join:
                    left:
                        category:
                            join:  c.category
                            alias: category
                        categoryTranslation:
                            join:          category.translations
                            alias:         ct
                            conditionType: WITH
                            condition:     ct.locale = :localeCode
        columns:
            code:
                label: Code
            label:
                label: Label
            category:
                label:     Category tree
                data_name: categoryLabel
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_catalog_channel_edit
                params:
                    - id
            delete_link:
                type: url
                route: pim_catalog_channel_remove
                params:
                    - id
        actions:
            edit:
                type:      navigate
                label:     Edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete
                icon:  trash
                link:  delete_link
        sorters:
            columns:
                code:
                    data_name: c.code
                label:
                    data_name: c.label
                category:
                    data_name: categoryLabel
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: c.code
                label:
                    type:      string
                    label:     Label
                    data_name: c.label
                category:
                    type:      choice
                    label:     Category tree
                    data_name: categoryLabel
                    options:
                        field_options:
                            choices: @pim_catalog.manager.category->getTrees

    product-grid:
        flexible_entity: %pim_catalog.entity.product.class%
        options:
            entityHint: product
        source:
            acl_resource: pim_catalog_product_index
            type: orm_product
        columns:
             family:
                 label: Family
                 data_name: familyLabel
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_catalog_product_edit
                params:
                    - id
            delete_link:
                type: url
                route: pim_catalog_product_remove
                params:
                    - id
        actions:
            edit:
                type:      navigate
                label:     Edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete
                icon:  trash
                link:  delete_link
        sorters:
            columns: ~
                # family:
                #     data_name: family.code
            default:
                id: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                enabled:
                    type:      boolean
                    label:     Enabled
                    data_name: p.enabled
    family-grid:
        options:
            entityHint: family
        source:
            acl_resource: pim_catalog_family_index
            type: pim_orm
            entity: %pim_catalog.entity.family.class%
        columns:
            code:
                label: Code
            label:
                label: Label
            attributeAsLabel:
                label: Attribute as label
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_catalog_family_edit
                params:
                    - id
            delete_link:
                type: url
                route: pim_catalog_family_remove
                params:
                    - id
        actions:
            edit:
                type:      navigate
                label:     Edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete
                icon:  trash
                link:  delete_link
        sorters:
            columns:
                code:
                    data_name: f.code
                label:
                    data_name: label
                attributeAsLabel:
                    data_name: attributeAsLabel
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: f.code
                # TODO: need to create a translation filter
                label:
                    type: string
                    label: Label
                    data_name: f.translation.label
                # TODO: custom filter to get attribute label
                attributeAsLabel:
                    type:             entity
                    label:            Attribute as label
                    data_name:        attributeAsLabel
                    options:
                        field_options:
                            class: %pim_catalog.entity.product_attribute.class%
                            property: code

