services:
    pim_catalog.event_listener.association_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
          - localeCode
          - @oro_datagrid.datagrid.request_params
          - false
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.association-grid, method: onBuildAfter }

    pim_catalog.event_listener.attribute_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
          - localeCode
          - @oro_datagrid.datagrid.request_params
          - false
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.attribute-grid, method: onBuildAfter }

    pim_catalog.event_listener.channel_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
          - localeCode
          - @oro_datagrid.datagrid.request_params
          - false
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.channel-grid, method: onBuildAfter }
