_welcome:
    pattern:  /
    defaults: { _controller: StrixosDashboardBundle:Default:index }

StrixosDashboardBundle:
    resource: "@StrixosDashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard/

StrixosWidgetBundle:
    resource: "@StrixosWidgetBundle/Controller/"
    type:     annotation
    prefix:   /widget/

StrixosCoreBundle:
    resource: "@StrixosCoreBundle/Controller/"
    type:     annotation
    prefix:   /core/

StrixosDataFlowBundle:
    resource: "@StrixosDataFlowBundle/Controller/"
    type:     annotation
    prefix:   /dataflow/

StrixosReportBundle:
    resource: "@StrixosReportBundle/Controller/"
    type:     annotation
    prefix:   /report/

StrixosCatalogBundle:
    resource: "@StrixosCatalogBundle/Controller/"
    type:     annotation
    prefix:   /catalog/

StrixosIcecatConnectorBundle:
    resource: "@StrixosIcecatConnectorBundle/Controller/"
    type:     annotation
    prefix:   /icecatconnector/

bap_flexible_entity:
    resource: "@BapFlexibleEntityBundle/Controller/"
    type:     annotation
    prefix:   /bapflexibleentity/

AkeneoCatalogBundle:
    resource: "@AkeneoCatalogBundle/Controller/"
    type:     annotation
    prefix:   /newcat/
