_welcome:
    pattern:  /
    defaults: { _controller: PimDashboardBundle:Default:index }

pim_dashboard:
    resource: "@PimDashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard/

pim_connectoricecat:
    resource: "@PimConnectorIcecatBundle/Controller/"
    type:     annotation
    prefix:   /icecatconnector/

pim_catalog:
    resource: "@PimCatalogBundle/Controller/"
    type:     annotation
    prefix:   /catalog/
