StrixosDataFlowBundle:
    resource: "@StrixosDataFlowBundle/Controller/"
    type:     annotation
    prefix:   /dataflow/

StrixosReportBundle:
    resource: "@StrixosReportBundle/Controller/"
    type:     annotation
    prefix:   /report/

StrixosCatalogBundle:
    resource: "@StrixosCatalogBundle/Controller/"
    type:     annotation
    prefix:   /catalog/
