_welcome:
    pattern:  /{_locale}
    defaults: { _controller: PimUIBundle:Welcome:index, _locale: %locale% }

pim_default:
    pattern:  /{_locale}
    defaults:
        template:    PimUIBundle:Welcome:index.html.twig
        _locale:     %locale%
        _controller: FrameworkBundle:Template:template
    requirements:
        _locale:  en|fr|de

oro_user:
    resource: "@OroUserBundle/Resources/config/routing.yml"
    prefix: /user

pim_product:
    resource: "@PimProductBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/product/
    defaults: { _locale: %locale% }

pim_config:
    resource: "@PimConfigBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/config/
    defaults: { _locale: %locale% }