ext_strixos:
    resource: "@ExtStrixosBundle/Controller/"
    type:     annotation
    prefix:   /

biz_strixos:
    resource: "@BizStrixosBundle/Controller/"
    type:     annotation
    prefix:   /

biz_catalog:
    resource: "@BizCatalogBundle/Controller/"
    type:     annotation
    prefix:   /

bap_flexible_entity:
    resource: "@BapFlexibleEntityBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: StrixosDashboardBundle:Default:index }

StrixosDashboardBundle:
    resource: "@StrixosDashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard/

StrixosWidgetBundle:
    resource: "@StrixosWidgetBundle/Controller/"
    type:     annotation
    prefix:   /widget/

StrixosCoreBundle:
    resource: "@StrixosCoreBundle/Controller/"
    type:     annotation
    prefix:   /core/

StrixosDataFlowBundle:
    resource: "@StrixosDataFlowBundle/Controller/"
    type:     annotation
    prefix:   /dataflow/

StrixosReportBundle:
    resource: "@StrixosReportBundle/Controller/"
    type:     annotation
    prefix:   /report/

StrixosCatalogBundle:
    resource: "@StrixosCatalogBundle/Controller/"
    type:     annotation
    prefix:   /catalog/

StrixosIcecatConnectorBundle:
    resource: "@StrixosIcecatConnectorBundle/Controller/"
    type:     annotation
    prefix:   /icecatconnector/