_welcome:
    pattern:  /
    defaults: { _controller: StrixosDashboardBundle:Default:index }

StrixosDashboardBundle:
    resource: "@StrixosDashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard/

StrixosCoreBundle:
    resource: "@StrixosCoreBundle/Controller/"
    type:     annotation
    prefix:   /core/

StrixosDataFlowBundle:
    resource: "@StrixosDataFlowBundle/Controller/"
    type:     annotation
    prefix:   /dataflow/

StrixosReportBundle:
    resource: "@StrixosReportBundle/Controller/"
    type:     annotation
    prefix:   /report/

StrixosCatalogBundle:
    resource: "@StrixosCatalogBundle/Controller/"
    type:     annotation
    prefix:   /catalog/

StrixosIcecatConnectorBundle:
    resource: "@StrixosIcecatConnectorBundle/Controller/"
    type:     annotation
    prefix:   /icecatconnector/

bap_flexible_entity:
    resource: "@BapFlexibleEntityBundle/Controller/"
    type:     annotation
    prefix:   /bapflexibleentity/

AkeneoCatalogBundle:
    resource: "@AkeneoCatalogBundle/Controller/"
    type:     annotation
    prefix:   /newcat/

pim_user:
    resource: "@PimUserBundle/Controller/"
    type:     annotation
    prefix:   /user/

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
