_welcome:
    pattern:  /
    defaults: { _controller: StrixosDashboardBundle:Default:index }

StrixosDashboardBundle:
    resource: "@StrixosDashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard/

StrixosWidgetBundle:
    resource: "@StrixosWidgetBundle/Controller/"
    type:     annotation
    prefix:   /widget/

StrixosCoreBundle:
    resource: "@StrixosCoreBundle/Controller/"
    type:     annotation
    prefix:   /core/

StrixosDataFlowBundle:
    resource: "@StrixosDataFlowBundle/Controller/"
    type:     annotation
    prefix:   /dataflow/

StrixosReportBundle:
    resource: "@StrixosReportBundle/Controller/"
    type:     annotation
    prefix:   /report/

StrixosCatalogBundle:
    resource: "@StrixosCatalogBundle/Controller/"
    type:     annotation
    prefix:   /catalog/
