default:
    class: Pim\Bundle\InstallerBundle\FixtureLoader\Loader
    order: 100
    csv:
        reader:            pim_import_export.reader.file.csv
        reader_options:    {}
        processor_options: {}
    yml:
        reader:            pim_import_export.reader.file.yaml
        reader_options:    {}
        processor_options: {}

associations:
    order: 50
    csv:
        processor:         pim_import_export.processor.association
    yml:
        processor:         pim_import_export.processor.association

products:
    csv:
        processor:         pim_import_export.processor.product
    yml:
        reader_options:
            code_field: false
            homogenize: true
        processor:         pim_import_export.processor.product
