default:
    class: Pim\Bundle\InstallerBundle\FixtureLoader\Loader
    order: 100
    csv:
        reader:            pim_import_export.reader.file.csv
        reader_options:    {}
        processor_options: {}
    yml:
        reader:            pim_import_export.reader.file.yaml
        reader_options:    {}
        processor_options: {}

attribute_groups:
    order: 30
    csv:
        processor:         pim_import_export.processor.attribute_group
    yml:
        processor:         pim_import_export.processor.attribute_group

channels:
    order: 30
    csv:
        processor:         pim_import_export.processor.channel
    yml:
        processor:         pim_import_export.processor.channel

group_types:
    order: 30
    csv:
        processor:         pim_import_export.processor.group_type
    yml:
        processor:         pim_import_export.processor.group_type

associations:
    order: 50
    csv:
        processor:         pim_import_export.processor.association
    yml:
        processor:         pim_import_export.processor.association

attribute_options:
    order: 50
    csv:
        processor:         pim_import_export.processor.attribute_option
    yml:
        processor:         pim_import_export.processor.attribute_option

families:
    order: 60
    yml:
        processor:         pim_import_export.processor.nested_family

products:
    order: 90
    csv:
        processor:         pim_import_export.processor.product
    yml:
        reader_options:
            code_field: false
            homogenize: true
        processor:         pim_import_export.processor.product

jobs:
    order: 90
    csv:
        processor:         pim_import_export.processor.job_instance
    yml:
        processor:         pim_import_export.processor.job_instance
