parameters:
    pim_installer.transformer.guesser.fixture_reference.class:       Pim\Bundle\InstallerBundle\Transformer\Guesser\FixtureReferenceGuesser

services:
    pim_installer.transformer.guesser.fixture_reference:
        class: %pim_installer.transformer.guesser.fixture_reference.class%
        arguments:
            - '@pim_installer.transformer.property.fixture_reference'
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 150 }
