jobs:
    product_import:
        connector: Akeneo CSV Connector
        alias:     product_import
        label:     Demo product import
        type:      import
        steps:
            import:
                reader:
                    filePath:      /tmp/product.csv
                    uploadAllowed: true
                    delimiter:     ;
                    enclosure:     '"'
                    escape:        '\'
                processor:
                    enabled:          true
                    categoriesColumn: categories
                    familyColumn:     family
                    groupsColumn:     groups
                writer:
                    realTimeVersioning: true
            import_associations:
                reader:
                    filePath:      /tmp/product.csv
                    uploadAllowed: true
                    delimiter:     ;
                    enclosure:     '"'
                    escape:        '\'
    product_export:
        connector: Akeneo CSV Connector
        alias:     product_export
        label:     Demo product export
        type:      export
        steps:
            export:
                reader:
                    channel: mobile
                processor:
                    channel:    mobile
                    delimiter:  ;
                    enclosure:  '"'
                    withHeader: true
                writer:
                    filePath: /tmp/product.csv
    category_import:
        connector: Akeneo CSV Connector
        alias:     category_import
        label:     Demo category import
        type:      import
        steps:
            import:
                reader:
                    filePath:      /tmp/category.csv
                    uploadAllowed: true
                    delimiter:     ;
                    enclosure:     '"'
                    escape:        '\'
                processor:
                    circularRefsChecked: true
    category_export:
        connector: Akeneo CSV Connector
        alias:     category_export
        label:     Demo category export
        type:      export
        steps:
            export:
                processor:
                    delimiter:  ;
                    enclosure:  '"'
                    withHeader: true
                writer:
                    filePath: /tmp/category.csv
    association_import:
        connector: Akeneo CSV Connector
        alias:     association_import
        label:     Demo association import
        type:      import
        steps:
            import:
                reader:
                    filePath:      /tmp/association.csv
                    uploadAllowed: true
                    delimiter:     ;
                    enclosure:     '"'
                    escape:        '\'
    association_export:
        connector: Akeneo CSV Connector
        alias:     association_export
        label:     Demo association export
        type:      export
        steps:
            export:
                processor:
                    delimiter:  ;
                    enclosure:  '"'
                    withHeader: true
                writer:
                    filePath: /tmp/association.csv
    group_import:
        connector: Akeneo CSV Connector
        alias:     group_import
        label:     Demo group import
        type:      import
        steps:
            import:
                reader:
                    filePath:      /tmp/group.csv
                    uploadAllowed: true
                    delimiter:     ;
                    enclosure:     '"'
                    escape:        '\'
    group_export:
        connector: Akeneo CSV Connector
        alias:     group_export
        label:     Demo group export
        type:      export
        steps:
            export:
                processor:
                    delimiter:  ;
                    enclosure:  '"'
                    withHeader: true
                writer:
                    filePath: /tmp/group.csv
    attribute_import:
        connector: Akeneo CSV Connector
        alias:     attribute_import
        label:     Demo attribute import
        type:      import
        steps:
            import:
                reader:
                    filePath:      /tmp/attribute.csv
                    uploadAllowed: true
                    delimiter:     ;
                    enclosure:     '"'
                    escape:        '\'
    attribute_export:
        connector: Akeneo CSV Connector
        alias:     attribute_export
        label:     Demo attribute export
        type:      export
        steps:
            export:
                processor:
                    delimiter:  ;
                    enclosure:  '"'
                    withHeader: true
                writer:
                    filePath: /tmp/attribute.csv
    option_import:
        connector: Akeneo CSV Connector
        alias:     attribute_option_import
        label:     Demo option import
        type:      import
        steps:
            import:
                reader:
                    filePath:      /tmp/option.csv
                    uploadAllowed: true
                    delimiter:     ;
                    enclosure:     '"'
                    escape:        '\'
    option_export:
        connector: Akeneo CSV Connector
        alias:     attribute_option_export
        label:     Demo option export
        type:      export
        steps:
            export:
                processor:
                    delimiter:  ;
                    enclosure:  '"'
                    withHeader: true
                writer:
                    filePath: /tmp/option.csv
