oro_menu_config:
    items:
        pim_import_tab:
            label: 'Extract'
            uri: '#'
            extras:
                position: 10
        pim_export_tab:
            label: 'Spread'
            uri: '#'
            extras:
                position: 30
        pim_configuration_tab:
            label: 'Settings'
            uri: '#'
            extras:
                position: 50
        system_tab:
            label: 'System'
            extras:
                position: 60
        pim_config_locale:
            label: 'Locales'
            route: 'pim_config_locale_index'
        pim_config_currency:
            label: 'Currencies'
            route: 'pim_config_currency_index'
        pim_config_channel:
            label: 'Channels'
            route: 'pim_config_channel_index'

    tree:
        application_menu:
            children:
                pim_configuration_tab:
                    children:
                        pim_config_currency: ~
                        pim_config_locale: ~

                pim_export_tab:
                    children:
                        pim_config_channel: ~

