oro_menu_config:
    items:
        pim_config_locale:
            label: 'Locales'
            route: 'pim_config_locale_index'
        pim_config_currency:
            label: 'Currencies'
            route: 'pim_config_currency_index'
        pim_config_channel:
            label: 'Channels'
            route: 'pim_config_channel_index'

    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        pim_config_channel: ~
                        pim_config_locale: ~
                        pim_config_currency: ~

