parameters:
    language_entity_class:  Pim\Bundle\ConfigBundle\Entity\Language
    language_handler_class: Pim\Bundle\ConfigBundle\Form\Handler\LanguageHandler
    language_manager_class: Oro\Bundle\FlexibleEntityBundle\Manager\SimpleManager
    language_type_class:    Pim\Bundle\ConfigBundle\Form\Type\LanguageType

services:
    # Managers
    language_manager:
        class:     "%language_manager_class%"
        arguments: ["%language_entity_class%", "@doctrine.orm.entity_manager"]
        
    
    # Form
    pim_config.form.language:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["pim_config_language_form", "pim_config_language"]
            
    pim_config.form.type.language:
        class:  %language_type_class%
        tags:
            - { name: form.type, alias: pim_config_language }
    
    # Handlers
    pim_config.form.handler.language:
        class:  %language_handler_class%
        scope: request
        arguments: ["@pim_config.form.language", "@request", "@doctrine.orm.entity_manager"]
        