parameters:
    currency_entity_class:  Pim\Bundle\ConfigBundle\Entity\Currency
    currency_handler_class: Pim\Bundle\ConfigBundle\Form\Handler\CurrencyHandler
    currency_type_class:    Pim\Bundle\ConfigBundle\Form\Type\CurrencyType
    currency_grid_manager_class: Pim\Bundle\ConfigBundle\Datagrid\CurrencyDatagridManager
    
    language_entity_class:  Pim\Bundle\ConfigBundle\Entity\Language
    language_handler_class: Pim\Bundle\ConfigBundle\Form\Handler\LanguageHandler
    language_type_class:    Pim\Bundle\ConfigBundle\Form\Type\LanguageType
    locale_grid_manager_class: Pim\Bundle\ConfigBundle\Datagrid\LocaleDatagridManager
    
    channel_entity_class:   Pim\Bundle\ConfigBundle\Entity\Channel
    channel_handler_class:  Pim\Bundle\ConfigBundle\Form\Handler\ChannelHandler
    channel_type_class:     Pim\Bundle\ConfigBundle\Form\Type\ChannelType

services:
    # DataGrid
    pim_config.datagrid.manager.locale:
        class: %locale_grid_manager_class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: locales
              entity_hint: locales
              route_name: pim_config_language_index
        calls:
            - [ setRouter, [ @router ] ]
            - [ setBaseActionUrl, ["pim_config_language"] ]
            
    pim_config.datagrid.manager.currency:
        class: %currency_grid_manager_class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: currencies
              route_name: pim_config_currency_index
    
    # Managers
    pim_config.manager.locale:
        class:     Pim\Bundle\ConfigBundle\Manager\LocaleManager
        arguments: [@doctrine.orm.entity_manager]
    
    # Form
    pim_config.form.channel:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments: ["pim_config_channel_form", "pim_config_channel"]
    
    pim_config.form.currency:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments: ["pim_config_currency_form", "pim_config_currency"]
        
    pim_config.form.language:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments: ["pim_config_language_form", "pim_config_language"]

    # Types
    pim_config.form.type.channel:
        class: %channel_type_class%
        tags:
            - { name: form.type, alias: pim_config_channel }
    
    pim_config.form.type.currency:
        class: %currency_type_class%
        arguments: [%pim_config.currencies%]
        tags:
            - { name: form.type, alias: pim_config_currency }
    
    pim_config.form.type.language:
        class: %language_type_class%
        arguments: [%pim_config.languages%]
        tags:
            - { name: form.type, alias: pim_config_language }
    
    # Handlers
    pim_config.form.handler.channel:
        class: %channel_handler_class%
        scope: request
        arguments: [@pim_config.form.channel, @request, @doctrine.orm.entity_manager]
    
    pim_config.form.handler.currency:
        class: %currency_handler_class%
        scope: request
        arguments: [@pim_config.form.currency, @request, @doctrine.orm.entity_manager]
    
    pim_config.form.handler.language:
        class: %language_handler_class%
        scope: request
        arguments: [@pim_config.form.language, @request, @doctrine.orm.entity_manager]
        