parameters:
    pim_config.event_listener.user_preferences.class:  Pim\Bundle\ConfigBundle\EventListener\UserPreferencesListener
    pim_config.event_listener.locale_activation.class: Pim\Bundle\ConfigBundle\EventListener\LocaleActivationListener
    
services:
    # Subscriber
    pim_config.event_listener.user_preferences:
        class: %pim_config.event_listener.user_preferences.class%
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }
            
    pim_config.event_listener.locale_activation:
        class: %pim_config.event_listener.locale_activation.class%
        calls:
            - [ setContainer, [@service_container ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # Validators
    pim_config.validator.valid_locale_fallback:
        class: Pim\Bundle\ConfigBundle\Validator\Constraints\ValidLocaleFallbackValidator
        arguments:
            - @doctrine.orm.entity_manager
        tags:
        - { name: validator.constraint_validator, alias: pim_config.validator.valid_locale_fallback_validator }
