Oro\Bundle\UserBundle\Entity\User:
    fields:
        catalogLocale:
            type: manyToOne
            configs:
                entity:
                    label: Catalog locale
                form:
                    is_enabled: true
                view:
                    is_displayable: true
                dataaudit:
                    auditable: false
                email:
                    available_in_template: false
                extend:
                    owner:         Custom
                    is_extend:     false
                    extend:        true
                    is_deleted:    false
                    is_inverse:    false
                    target_entity: Pim\Bundle\CatalogBundle\Entity\Locale
                    target_field:  code
        catalogScope:
            type: manyToOne
            configs:
                entity:
                    label: Catalog scope
                form:
                    is_enabled: true
                view:
                    is_displayable: true
                dataaudit:
                    auditable: false
                email:
                    available_in_template: false
                extend:
                    owner:         Custom
                    is_extend:     false
                    extend:        true
                    is_deleted:    false
                    is_inverse:    false
                    target_entity: Pim\Bundle\CatalogBundle\Entity\Channel
                    target_field:  code
        defaultTree:
            type: manyToOne
            configs:
                entity:
                    label: Default tree
                form:
                    is_enabled: true
                view:
                    is_displayable: true
                dataaudit:
                    auditable: false
                email:
                    available_in_template: false
                extend:
                    owner:         Custom
                    is_extend:     false
                    extend:        true
                    is_deleted:    false
                    is_inverse:    false
                    target_entity: Pim\Bundle\CatalogBundle\Entity\Category
                    target_field:  code
