Oro\Bundle\UserBundle\Entity\User:
    fields:
        catalogLocale:
            type: manyToOne
            configs:
                entity:
                    label: Catalog locale
                form:
                    is_enabled: true
                view:
                    is_displayable: true
                dataaudit:
                    auditable: false
                email:
                    available_in_template: false
                extend:
                    owner: Custom
                    is_extend: false
                    extend: true
                    is_deleted: 0
                    is_inverse: 0
                    target_entity: Pim\Bundle\CatalogBundle\Entity\Locale
                    target_field: code
                    relation_key: manyToOne|Oro\Bundle\UserBundle\Entity\User|Pim\Bundle\CatalogBundle\Entity\Locale|catalogLocale
        catalogScope:
            type: manyToOne
            configs:
                entity:
                    label: Catalog scope
                form:
                    is_enabled: true
                view:
                    is_displayable: true
                dataaudit:
                    auditable: false
                email:
                    available_in_template: false
                extend:
                    owner: Custom
                    is_extend: false
                    extend: true
                    is_deleted: 0
                    is_inverse: 0
                    target_entity: Pim\Bundle\CatalogBundle\Entity\Channel
                    target_field: code
                    relation_key: manyToOne|Oro\Bundle\UserBundle\Entity\User|Pim\Bundle\CatalogBundle\Entity\Channel|catalogScope
        defaultTree:
            type: manyToOne
            configs:
                entity:
                    label: Default tree
                form:
                    is_enabled: true
                view:
                    is_displayable: true
                dataaudit:
                    auditable: false
                email:
                    available_in_template: false
                extend:
                    owner: Custom
                    is_extend: false
                    extend: true
                    is_deleted: 0
                    is_inverse: 0
                    target_entity: Pim\Bundle\CatalogBundle\Entity\Category
                    target_field: code
                    relation_key: manyToOne|Oro\Bundle\UserBundle\Entity\User|Pim\Bundle\CatalogBundle\Entity\Category|defaultTree
