parameters:
    pim_translation.translatable_field_class: Pim\Bundle\TranslationBundle\Form\Type\TranslatableFieldType

services:
    pim_translation.form.type.translatable_field:
        class: %pim_translation.translatable_field_class%
        arguments:
            - @validator
            - @pim_config.manager.locale
            - %default_locale%
        tags:
            - { name: form.type, alias: pim_translatable_field }
