parameters:
    pim_icecat_connector.connectorservice.class: Pim\Bundle\ConnectorIcecatBundle\Service\ConnectorService

services:
    # expose connector as a service
    akeneo.connector.icecat_service:
        class: "%pim_icecat_connector.connectorservice.class%"
        arguments: ["@service_container"]
        tags:
          - { name: akeneo.connector }

    # add menu items
    bap_ui.menu_listener_main: # first change the menu name
        class: Bap\Bundle\UIBundle\EventsListener\ConfigureMenuListener
        tags:
          - { name: kernel.event_listener, event: 'BapMainMenu_event', method: onMenuConfigure } # second change the event created previously
        arguments:
            menu:    # after the menu definition there's the menu children to add
              root:  # this is the name of the node where to add the following children
                  Connectors:  # name of the child
                      route: '_welcome'

              Connectors: # this is the name of the node where you want add the following children (so below matches2)
                  IceCat:
                      route: 'pim_connectoricecat_config_edit'

                  Catalog:
                      route: 'pim_connectoricecat_config_edit'

              IceCat: # this is the name of the node where you want add the following children (so below matches2)
                  Settings:
                      route: 'pim_connectoricecat_config_edit'
                  Suppliers:
                      route: 'pim_connectoricecat_supplier_list'
                  Products:
                      route: 'pim_connectoricecat_product_list'


