services:

    # Handlers
    pim_product.form.handler.basic_product:
        class: %pim_product.handler.basic_product.class%
        scope: request
        arguments: [@pim_product.form.basic_product, @request, @pim_product.manager.product]

    pim_product.form.handler.attribute:
        class: %pim_product.form.handler.product_attribute.class%
        scope: request
        arguments: [@pim_product.form.attribute, @request, @doctrine.orm.entity_manager, @pim_product.manager.attribute_type]

    pim_product.form.handler.attribute_group:
        class: %pim_product.handler.attribute_group.class%
        scope: request
        arguments: [@pim_product.form.attribute_group, @request, @doctrine.orm.entity_manager]

    pim_product.form.handler.export_profile:
        class: %pim_product.handler.export_profile.class%
        scope: request
        arguments: [@pim_product.form.export_profile, @request, @doctrine.orm.entity_manager]
