api:
    resource: "@PimProductBundle/Controller/Api/ProductController.php"
    type:         rest
    prefix:       api/rest/{scope}/

attributegroup:
    resource: "@PimProductBundle/Resources/config/routing/attributegroup.yml"
    prefix: /configuration/attribute-group

channel:
    resource: "@PimProductBundle/Resources/config/routing/channel.yml"
    prefix: /configuration/channel

currency:
    resource: "@PimProductBundle/Resources/config/routing/currency.yml"
    prefix: /configuration/currency

family:
    resource: "@PimProductBundle/Resources/config/routing/family.yml"
    prefix: /configuration/family

locale:
    resource: "@PimProductBundle/Resources/config/routing/locale.yml"
    prefix: /configuration/locale

productattribute:
    resource: "@PimProductBundle/Resources/config/routing/productattribute.yml"
    prefix: /configuration/attribute

categorytree:
    resource: "@PimProductBundle/Resources/config/routing/categorytree.yml"
    prefix: /enrich/category-tree

product:
    resource: "@PimProductBundle/Resources/config/routing/product.yml"
    prefix: /enrich/product
