Pim\Bundle\ProductBundle\Entity\ProductAttribute:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        code:
            - NotBlank: ~
            - Regex:
                pattern: "/^[a-zA-Z0-9_]+$/"
                message: "Attribute name may contain only letters, numbers and underscores"
            - Length:
                max: 255
        description:
            - Length:
                max: 255
        searchable:
            - Type: bool
        translatable:
            - Type: bool
        useableAsGridColumn:
            - Type: bool
        useableAsGridFilter:
            - Type: bool
        wysiwygEnabled:
            - Type: bool
        valueCreationAllowed:
            - Type: bool
        decimalsAllowed:
            - Type: bool
        negativeAllowed:
            - Type: bool
        maxFileSize:
            - Type: int
        sortOrder:
            - Type: int
        maxCharacters:
            - Type: int
