Pim\Bundle\ProductBundle\Entity\ProductAttribute:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        code:
            - NotBlank: ~
            - Regex:
                pattern: "/^[a-zA-Z0-9_]+$/"
                message: "Attribute name may contain only letters, numbers and underscores"
            - Length:
                max: 255
        description:
            - Length:
                max: 255
