Pim\Bundle\ProductBundle\Entity\ProductAttribute:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        code:
            - NotBlank: ~
            - Regex:
                pattern: "/^[a-zA-Z0-9_]+$/"
                message: "Attribute name may contain only letters, numbers and underscores"
            - Length:
                max: 255
        description:
            - Length:
                max: 255
        searchable:
            - Type: bool
        translatable:
            - Type: bool
        useableAsGridColumn:
            - Type: bool
        useableAsGridFilter:
            - Type: bool
        wysiwygEnabled:
            - Type: bool
        valueCreationAllowed:
            - Type: bool
        decimalsAllowed:
            - Type: bool
        negativeAllowed:
            - Type: bool
        maxCharacters:
            - Type: int
        maxFileSize:
            - Type: int
        sortOrder:
            - Type: int
        unique:
            - Type: bool
            - "False":
                message: This attribute type can't have unique value
                groups:
                    - pim_product_textarea
                    - pim_product_price_collection
                    - pim_product_multiselect
                    - pim_product_simpleselect
                    - pim_product_image
                    - pim_product_file
                    - pim_product_metric
                    - pim_product_boolean
        options:
            - Count:
                min: 1
                minMessage: You must specify at least one option
                groups: [pim_product_simpleselect, pim_product_multiselect]
        dateType:
            - Choice:
                choices: [date, time, datetime]
                groups: [pim_product_date]
        allowedFileSources:
            - Choice:
                choices: [upload, external]
                groups: [pim_product_file, pim_product_image]
        maxFileSize:
            - Type:
                type: integer
                groups: [pim_product_file, pim_product_image]
            - GreaterThanOrEqual:
                value: 0
                groups: [pim_product_file, pim_product_image]
        defaultValue:
            - Blank:
                message: No default value may be specified for this attribute type
                groups: [pim_product_file, pim_product_image, pim_product_identifier]
            - Type:
                type: bool
                groups: [pim_product_boolean]
