config:
    shim:
        'jquery.slimbox':
            deps:
                - 'jquery'
        'bootstrap.bootstrapswitch':
            deps:
                - 'jquery'
        'selectize':
            deps:
                - 'jquery'
                - 'sifter'
                - 'microplugin'
        'jquery.sidebarize':
            deps:
                - 'jquery'
        'jquery.currencyfield':
            deps:
                - 'jquery'
        'jquery.wizard':
            deps:
                - 'jquery'
        'jstree/jquery.jstree.nested_switch':
            deps:
                - 'jquery.jstree'

    paths:
#        'jquery-ui':                              'pimui/lib/jquery/jquery-ui-1.10.3.custom.min'
#        'jquery.uniform':                         'pimui/lib/jquery/jquery.uniform.min'
        'jquery.slimbox':                         'bundles/pimui/js/slimbox2'
        'bootstrap.bootstrapswitch':              'bundles/oroui/lib/bootstrap/js/bootstrap.switch'
        'selectize':                              'bundles/pimui/lib/selectize'
        'sifter':                                 'bundles/pimui/lib/sifter'
        'microplugin':                            'bundles/pimui/lib/microplugin'
        'jquery.currencyfield':                   'bundles/pimui/js/jquery.currencyfield'
        'jquery.sidebarize':                      'bundles/pimui/js/jquery.sidebarize'
        'jquery.wizard':                          'bundles/pimcatalog/js/jquery.wizard'
        'jstree/jquery.jstree.nested_switch':     'bundles/pimcatalog/js/lib/jstree/jquery.jstree.nested_switch'
        'pim/init':                               'bundles/pimui/js/pim-init'
        'pim/initselect2':                        'bundles/pimui/js/pim-initselect2'
        'pim/dialog':                             'bundles/pimui/js/pim-dialog'
        'pim/formupdatelistener':                 'bundles/pimui/js/pim-formupdatelistener'
        'pim/popinform':                          'bundles/pimui/js/pim-popinform'
        'pim/dialogform':                         'bundles/pimui/js/pim-dialogform'
        'pim/scopable':                           'bundles/pimui/js/pim-scopable'
        'pim/datafilter/currency-filter':         'bundles/pimfilter/js/datafilter/filter/currency-filter'
        'pim/datafilter/metric-filter':           'bundles/pimfilter/js/datafilter/filter/metric-filter'
        'pim/datafilter/scope-filter':            'bundles/pimfilter/js/datafilter/filter/scope-filter'
        'pim/tree/associate':                     'bundles/pimcatalog/js/tree-associate.jstree'
#        'pim/tree/mass-associate':                'bundles/pimcatalog/js/tree-mass-associate.jstree'
        'pim/tree/manage':                        'bundles/pimcatalog/js/tree-manage.jstree'
        'pim/tree/view':                          'bundles/pimcatalog/js/tree-view.jstree'
        'pim/datagrid/grid':                      'bundles/pimgrid/js/datagrid/pim-grid'
        'pim/datagrid/export-action':             'bundles/pimgrid/js/datagrid/action/export-collection-action'
        'pim/datagrid/tab-redirect-action':       'bundles/pimgrid/js/datagrid/action/tab-redirect-action'
        'pim/datagrid/product-delete-action':     'bundles/pimgrid/js/datagrid/action/product-delete-action'
#        'oro/datagrid/column-form-listener':      'pimgrid/js/datagrid/listener/column-form-listener'
#        'oro/datagrid/column-form-listener-orig': 'orogrid/js/datagrid/listener/column-form-listener'
        'pim/datagrid/parameter-setter':          'bundles/pimgrid/js/datagrid/parameter-setter'
#        'oro/datagrid/router-orig':               'orogrid/js/datagrid/router'
#        'oro/datagrid/router':                    'pimgrid/js/datagrid/router'
#        'oro/pageable-collection-orig':           'orogrid/js/pageable-collection'
#        'oro/pageable-collection':                'pimgrid/js/pageable-collection'
#        'oro/navigation-orig':                    'oronavigation/js/navigation'
#        'oro/navigation':                         'pimnavigation/js/navigation'
#        'oro/datagrid/reset-collection-action':   'pimgrid/js/datagrid/action/reset-collection-action'
        'pim/datagrid/toolbar':                   'bundles/pimgrid/js/datagrid/pim-toolbar'
        'jquery.bind-first': 'bundles/pimjsformvalidation/js/jquery.bind-first-0.2.0.min.js'
