jobs:
    product_import:
        connector: Akeneo CSV Connector
        alias:     product_import
        label:     Demo product import
        type:      import
        configuration:
            filePath:           /tmp/product.csv
            uploadAllowed:      true
            delimiter:          ;
            enclosure:          '"'
            escape:             '\'
            enabled:            true
            categoriesColumn:   categories
            familyColumn:       family
            groupsColumn:       groups
            realTimeVersioning: true
    product_export:
        connector: Akeneo CSV Connector
        alias:     product_export
        label:     Demo product export
        type:      export
        configuration:
            channel:    mobile
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/product.csv
    my_export:
        connector: Test Connector
        alias:     my_export
        label:     Demo export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
