pim_product_attributegroup_index:
    path: ""
    defaults: { _controller: PimProductBundle:AttributeGroup:create }

pim_product_attributegroup_create:
    path: /create
    defaults: { _controller: PimProductBundle:AttributeGroup:create }

pim_product_attributegroup_edit:
    path: /{id}/edit
    defaults: { _controller: PimProductBundle:AttributeGroup:edit }
    requirements:
        id: \d+

pim_product_attributegroup_sort:
    path: /sort
    defaults: { _controller: PimProductBundle:AttributeGroup:sort }
    methods: [POST]

pim_product_attributegroup_remove:
    path: /{id}/remove
    defaults: { _controller: PimProductBundle:AttributeGroup:remove }
    requirements:
        id: \d+
    methods: [DELETE]

pim_product_attributegroup_addproductattributes:
    path: /{id}/attributes
    defaults: { _controller: PimProductBundle:AttributeGroup:addProductAttributes }
    requirements:
        id: \d+
    methods: [POST]

pim_product_attributegroup_removeproductattribute:
    path: /{groupId}/attribute/{attributeId}/remove
    defaults: { _controller: PimProductBundle:AttributeGroup:removeProductAttribute }
    requirements:
        groupId: \d+
        attributeId: \d+
    methods: [DELETE]
