pim_product_categorytree_listtree:
    path: /list-tree.{_format}
    defaults: { _controller: PimProductBundle:CategoryTree:listTree }
    requirements:
        _format: json

pim_product_categorytree_movenode:
    path: /move-node
    defaults: { _controller: PimProductBundle:CategoryTree:moveNode }

pim_product_categorytree_children:
    path: /children.{_format}
    defaults: { _controller: PimProductBundle:CategoryTree:children }
    requirements:
        _format: json

pim_product_categorytree_listitems:
    path: /list-items.{_format}/{id}
    defaults: { _controller: PimProductBundle:CategoryTree:listItems }
    requirements:
        _format: json
        id: \d+

pim_product_categorytree_create:
    path: /create/{parent}
    defaults: { _controller: PimProductBundle:CategoryTree:create, parent: null }

pim_product_categorytree_edit:
    path: /{id}/edit
    defaults: { _controller: PimProductBundle:CategoryTree:edit }
    requirements:
        id: \d+

pim_product_categorytree_remove:
    path: /{id}/remove
    defaults: { _controller: PimProductBundle:CategoryTree:remove }
    requirements:
        id: \d+
    methods: [DELETE]
