pim_product_channel_index:
    path: /.{_format}
    defaults: { _controller: PimProductBundle:Channel:index, _format: html }
    requirements:
        _format: html|json

pim_product_channel_create:
    path: /create
    defaults: { _controller: PimProductBundle:Channel:create }

pim_product_channel_edit:
    path: /{id}/edit
    defaults: { _controller: PimProductBundle:Channel:edit }
    requirements:
        id: \d+

pim_product_channel_remove:
    path: /{id}/remove
    defaults: { _controller: PimProductBundle:Channel:remove }
    requirements:
        id: \d+
    methods: [DELETE]
