pim_product_currency_index:
    path: /.{_format}
    defaults: { _controller: PimProductBundle:Currency:index, _format: html }
    requirements:
        _format: html|json

pim_product_currency_toggle:
    path: /{id}/toggle
    defaults: { _controller: PimProductBundle:Currency:toggle }
    requirements:
        id: \d+
