pim_product_family_index:
    path: ""
    defaults: { _controller: PimProductBundle:Family:create }

pim_product_family_create:
    path: /create
    defaults: { _controller: PimProductBundle:Family:create }

pim_product_family_edit:
    path: /{id}/edit
    defaults: { _controller: PimProductBundle:Family:edit }
    requirements:
        id: \d+

pim_product_family_remove:
    path: /{id}/remove
    defaults: { _controller: PimProductBundle:Family:remove }
    requirements:
        id: \d+
    methods: [DELETE]

pim_product_family_addproductattributes:
    path: /{id}/attributes
    defaults: { _controller: PimProductBundle:Family:addProductAttributes }
    requirements:
        id: \d+
    methods: [POST]

pim_product_family_removeproductattribute:
    path: /{familyId}/attribute/{attributeId}/remove
    defaults: { _controller: PimProductBundle:Family:removeProductAttribute }
    requirements:
        familyId: \d+
        attributeId: \d+
    methods: [DELETE]
