Pim\Bundle\CatalogBundle\Model\GroupTranslation:
    type: embeddedDocument
    fields:
        id:
            id: true
        label:
            type: string
        locale:
            type: string
