Pim\Bundle\CatalogBundle\Model\Group:
    type: document
    collection: pim_catalog_group
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\MongoDBODM\GroupRepository
    fields:
        id:
            id: true
        code:
            type: string
        # References GroupType ORM entity code
        groupType:
            type: string
        # References ProductAttribute entity codes
        attributes:
            type: collection
        # Translations
        translations:
            embedded: true
            type: many
            targetDocument: Pim\Bundle\CatalogBundle\Model\GroupTranslation
        products:
            reference: true
            type: many
            # FIXME_MONGO: use productinterface and target resolver for MongoDB
            targetDocument: Pim\Bundle\CatalogBundle\Model\Product
