Pim\Bundle\CatalogBundle\Model\Product:
    type: document
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\MongoDBODM\ProductRepository
    collection: pim_catalog_product
    fields:
        id:
            id: true
            generator:
                strategy: AUTO
        enabled:
            type: boolean
        created:
            type: date
        updated:
            type: date
        # Family references ORM family code
        family:
            type: string
        groups:
            reference: true
            type: many
            targetDocument: Pim\Bundle\CatalogBundle\Model\Group
        # Collection to references ORM categories code
        categories:
            type: collection
        values:
            embedded: true
            type: many
#            targetDocument: Pim\Bundle\CatalogBundle\Model\ProductValueInterface
            targetDocument: Pim\Bundle\CatalogBundle\Model\ProductValue
