Pim\Bundle\CatalogBundle\Model\ProductValue:
    indexes:
        value_idx:
            options:
                unique: false
            keys:
                attribute_id:
                locale_code:
                scope_code:
    fields:
        id:
            id: true
        varchar:
            index: true
            type: string
        integer:
            type: int
            nullable: true
            column: value_integer
        decimal:
            type: float
        boolean:
            type: boolean
        text:
            type: string
        date:
            type: date
        datetime:
            type: date
        locale:
            type: string
        scope:
            type: string
        # References ORM ProductAttribute code
        attribute:
            type: string
        # References ORM AttributeOption code for single select
        option:
            type: string
        # References ORM AttributeOption code for multi selects
        options:
            type: collection
        media:
            embedded: true
            type: one
            targetDocument: Pim\Bundle\CatalogBundle\Model\Media
# Needs to get the metric as a Document
#        metric:
#            embedded: true
#            type: one
#            targetDocument: Pim\Bundle\FlexibleEntityBundle\Entity\Metric
        prices:
            embedded: true
            type: many
            targetDocument: Pim\Bundle\CatalogBundle\Model\ProductPrice
#            orderBy:
#                currency: ASC
