parameters:
    pim_catalog.event_listener.mongodb.inject_orm_references.class: Pim\Bundle\CatalogBundle\EventListener\MongoDBODM\InjectORMReferencesSubscriber

services:
    pim_catalog.object_manager.product:
        alias: doctrine.odm.mongodb.document_manager

    pim_catalog.event_listener.mongodb.inject_orm_references:
        class: %pim_catalog.event_listener.mongodb.inject_orm_references.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_catalog.entity.product_attribute.class%
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }
