parameters:
    pim_catalog.doctrine.completeness_generator.class:  Pim\Bundle\CatalogBundle\Doctrine\ORM\CompletenessGenerator

services:
    pim_catalog.object_manager.product:
        alias: "doctrine.orm.entity_manager"

    pim_catalog.object_manager.group:
        alias: "doctrine.orm.entity_manager"


    pim_catalog.doctrine.completeness_generator:
        class: %pim_catalog.doctrine.completeness_generator.class%
        arguments:
            - '@doctrine'
            - %pim_catalog.entity.product.class%
            - %pim_catalog.entity.product_value.class%
