jobs:
    product_import:
        connector: Akeneo CSV Connector
        alias:     product_import
        label:     Product import
        type:      import
        configuration:
            filePath:      /tmp/import/products.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
            enabled:          true
            categoriesColumn: categories
            familyColumn:     family
            groupsColumn:     groups
    ecommerce_product_export:
        connector: Akeneo CSV Connector
        alias:     product_export
        label:     Product export for ecommerce
        type:      export
        configuration:
            channel:    ecommerce
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/export/products_ecommerce.csv
    tablet_product_export:
        connector: Akeneo CSV Connector
        alias:     product_export
        label:     Product export for tablet
        type:      export
        configuration:
            channel:    tablet
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/export/products_tablet.csv
    print_product_export:
        connector: Akeneo CSV Connector
        alias:     product_export
        label:     Product export for print
        type:      export
        configuration:
            channel:    print
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/export/products_print.csv
    category_import:
        connector: Akeneo CSV Connector
        alias:     category_import
        label:     Category import
        type:      import
        configuration:
            filePath:            /tmp/import/categories.csv
            uploadAllowed:       true
            delimiter:           ;
            enclosure:           '"'
            escape:              '\'
            circularRefsChecked: true
    category_export:
        connector: Akeneo CSV Connector
        alias:     category_export
        label:     Category export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/export/categories.csv
    association_import:
        connector: Akeneo CSV Connector
        alias:     association_import
        label:     Association import
        type:      import
        configuration:
            filePath:      /tmp/import/associations.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    association_export:
        connector: Akeneo CSV Connector
        alias:     association_export
        label:     Association export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/export/associations.csv
    group_import:
        connector: Akeneo CSV Connector
        alias:     group_import
        label:     Group import
        type:      import
        configuration:
            filePath:      /tmp/import/groups.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    group_export:
        connector: Akeneo CSV Connector
        alias:     group_export
        label:     Group export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:  /tmp/export/groups.csv
    attribute_import:
        connector: Akeneo CSV Connector
        alias:     attribute_import
        label:     Attribute import
        type:      import
        configuration:
            filePath:      /tmp/import/attributes.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    attribute_export:
        connector: Akeneo CSV Connector
        alias:     attribute_export
        label:     Attribute export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/export/attributes.csv
    option_import:
        connector: Akeneo CSV Connector
        alias:     attribute_option_import
        label:     Option import
        type:      import
        configuration:
            filePath:      /tmp/import/options.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    option_export:
        connector: Akeneo CSV Connector
        alias:     attribute_option_export
        label:     Option export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/export/options.csv
