pim_navigation_collect:
    type: action
    label: pim_navigation.acl.collect

pim_navigation_enrich:
    type: action
    label: pim_navigation.acl.enrich

pim_navigation_spread:
    type: action
    label: pim_navigation.acl.spread

pim_navigation_settings:
    type: action
    label: pim_navigation.acl.settings

pim_navigation_system:
    type: action
    label: pim_navigation.acl.system
