_homepage:
    pattern:  /
    defaults: { _controller: StrixosCatalogBundle:Default:index }


_attributeset_index:
    pattern:  /attributeset/index
    defaults: { _controller: StrixosCatalogBundle:AttributeSet:index }


_attribute_index:
    pattern:  /attribute/index
    defaults: { _controller: StrixosCatalogBundle:Attribute:index }

_attribute_new:
    pattern:  /attribute/new
    defaults: { _controller: StrixosCatalogBundle:Attribute:new }

_attribute_edit:
    pattern:  /attribute/edit/{id}
    defaults: { _controller: StrixosCatalogBundle:Attribute:edit }

_attribute_save:
    pattern:  /attribute/save
    defaults: { _controller: StrixosCatalogBundle:Attribute:save }


_product_index:
    pattern:  /product/index
    defaults: { _controller: StrixosCatalogBundle:Product:index }

_product_edit:
    pattern:  /product/index
    defaults: { _controller: StrixosCatalogBundle:Product:index }
    
_product_delete:
    pattern:  /product/index
    defaults: { _controller: StrixosCatalogBundle:Product:index }

_product_search:
    pattern:  /product/search
    defaults: { _controller: StrixosCatalogBundle:Product:search }


_category_index:
    pattern:  /category/index
    defaults: { _controller: StrixosCatalogBundle:Category:index }
