_homepage:
    pattern:  /
    defaults: { _controller: StrixosCatalogBundle:Default:index }

_producttype_index:
    pattern:  /producttype/index
    defaults: { _controller: StrixosCatalogBundle:ProductType:index }

_product_index:
    pattern:  /product/index
    defaults: { _controller: StrixosCatalogBundle:Product:index }

_product_edit:
    pattern:  /product/index
    defaults: { _controller: StrixosCatalogBundle:Product:index }
    
_product_delete:
    pattern:  /product/index
    defaults: { _controller: StrixosCatalogBundle:Product:index }
