oro_menu_config:
    items:
        pim_export_connector:
            label: 'Olds UI'
            route: 'pim_batch_connector_index'

    tree:
        application_menu:
            children:
                pim_export_tab:
                    children:
                        pim_export_connector: ~

oro_titles:
    pim_batch_connector_index: Export management

