parameters:                                                                     
    pim_batch.simple_job.class: Pim\Bundle\BatchBundle\Job\SimpleJob

    pim_batch.connectors.class: Pim\Bundle\BatchBundle\DependencyInjection\Compiler\ConnectorRegistry
    pim_batch.connectors_config: ~
    pim_batch.jobs_config: ~

services:
    pim_batch.my_super_job:
        class:     %pim_batch.simple_job.class%
        arguments: ['My Super Job as a service !']
        tags:
            - { name: pim_batch.job }

    # connectors registry
    pim_batch.connectors:
        class: %pim_batch.connectors.class%
